"use strict";
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { DatabaseSync } = require("node:sqlite");
const { AccessControlStore, DAY_MS, DEFAULT_CHILD_PERMISSIONS, OWNER_PERMISSIONS, hashPassword, normalizeAccessDuration, publicSession, sessionIdentity } = require("./accessControl");
const { requiredPermission } = require("./securityAccess");
function makeStore(t) { const file = path.join(os.tmpdir(), `jarvis-access-${crypto.randomUUID()}.sqlite`); const db = new DatabaseSync(file); const store = new AccessControlStore({ db }); store.open(); t.after(() => { db.close(); fs.rmSync(file, { force: true }); }); return store; }

test("security is disabled and primary access remains available until explicit setup", (t) => { const store = makeStore(t); assert.deepEqual(store.publicSettings(), { enabled: false, recoveryRequired: false, autoLockMinutes: 0 }); assert.equal(sessionIdentity({ session: {} }), null); });
test("a malformed persisted access record requires explicit owner recovery", async (t) => { const store = makeStore(t); store.db.prepare("INSERT INTO jarvis_security_settings (id, admin_password_hash, auto_lock_minutes, updated_at) VALUES (1, ?, 15, ?)").run("not-a-valid-hash", new Date().toISOString()); assert.equal(store.securityState(), "recovery_required"); assert.equal(store.publicSettings().recoveryRequired, true); await assert.rejects(() => store.setup("replacement safe password"), /recovery/); await store.recover("replacement safe password"); assert.equal(await store.verifyAdmin("replacement safe password"), true); });
test("owner setup uses a salted scrypt hash and exposes no hash", async (t) => { const store = makeStore(t); await store.setup("correct horse battery staple", 15, "owner@example.test"); assert.equal(await store.verifyAdmin("correct horse battery staple"), true); assert.equal(await store.verifyAdmin("incorrect"), false); assert.deepEqual(store.publicSettings(), { enabled: true, recoveryRequired: false, autoLockMinutes: 15 }); assert.doesNotMatch(JSON.stringify(store.publicSettings()), /scrypt|horse/i); });
test("child profiles default to no permissions, respect disablement, and use bounded session expiry", async (t) => { const store = makeStore(t); await store.setup("correct horse battery staple", 0, "owner@example.test"); const child = await store.createChild({ displayName: "Workflow user", email: "workflow@example.test", password: "another safe password", sessionLimitMinutes: 15 }); assert.deepEqual(child.permissions, DEFAULT_CHILD_PERMISSIONS); assert.equal(Boolean(await store.verifyChild(child.id, "another safe password")), true); store.updateChild(child.id, { enabled: false }); assert.equal(await store.verifyChild(child.id, "another safe password"), null); const expiresAt = Date.now() + 1000; assert.equal(sessionIdentity({ session: { jarvisAuth: { role: "child", expiresAt } } }, expiresAt - 1).role, "child"); assert.equal(sessionIdentity({ session: { jarvisAuth: { role: "child", expiresAt } } }, expiresAt), null); });
test("custom access durations are server-normalized from one day through one year", async (t) => { const store = makeStore(t); const now = Date.now(); for (const [value, unit, days] of [[1, "days", 1], [7, "days", 7], [30, "days", 30], [6, "months", 180], [1, "year", 365], [12, "months", 365]]) { const normalized = normalizeAccessDuration(value, unit, now); assert.equal(normalized.accessExpiresAt, now + days * DAY_MS); const child = await store.createChild({ displayName: `${value} ${unit}`, email: `${value}-${unit}@example.test`, password: "another safe password", durationValue: value, durationUnit: unit }); assert.equal(child.durationValue, value); assert.equal(child.durationUnit, unit); assert.ok(child.accessExpiresAt > now); } });
test("server rejects manipulated durations above one year and expired profiles", async (t) => { const store = makeStore(t); for (const [value, unit] of [[0, "days"], [366, "days"], [24, "months"], [2, "year"], [-1, "weeks"]]) await assert.rejects(() => store.createChild({ displayName: "Invalid", email: "invalid@example.test", password: "another safe password", durationValue: value, durationUnit: unit }), /between|valid/); const child = await store.createChild({ displayName: "Expired", email: "expired@example.test", password: "another safe password", durationValue: 1, durationUnit: "days" }); store.db.prepare("UPDATE jarvis_child_profiles SET access_expires_at = ? WHERE id = ?").run(Date.now() - 1, child.id); assert.equal(await store.verifyChild(child.id, "another safe password"), null); });
test("public session grants full owner permissions and route policy is explicit", () => { const owner = publicSession({ session: { jarvisAuth: { role: "owner", displayName: "Owner" } } }); assert.deepEqual(owner.permissions, OWNER_PERMISSIONS); assert.equal(requiredPermission({ path: "/api/workflows", method: "GET" }), "view_workflow"); assert.equal(requiredPermission({ path: "/api/workflows", method: "POST" }), "edit_workflow"); assert.equal(requiredPermission({ path: "/api/workflow-executions/run", method: "POST" }), "run_workflow"); assert.equal(requiredPermission({ path: "/api/facebook/credentials", method: "POST" }), "publish_facebook"); assert.equal(requiredPermission({ path: "/api/google/credentials", method: "GET" }), "storage"); assert.equal(requiredPermission({ path: "/api/google/auth/start", method: "GET" }), "storage_modify"); assert.equal(requiredPermission({ path: "/api/ai/prepare-content", method: "POST" }), "run_workflow"); assert.equal(requiredPermission({ path: "/api/health", method: "GET" }), null); });

test("Admin reset tokens are hashed, expiring, single-use, and revoke only Admin sessions", async (t) => { const store = makeStore(t); await store.setup("old admin password", 0, " Owner@Example.com "); const adminSession = store.createSession("admin", { authVersion: store.settings().auth_version }); const childSession = store.createSession("child", { authVersion: 1 }); const token = store.createPasswordReset("owner@example.com", 1_000); assert.ok(token.length >= 40); const row = store.db.prepare("SELECT token_hash, expires_at FROM jarvis_password_resets").get(); assert.notEqual(row.token_hash, token); assert.equal(row.expires_at, 1_000 + 15 * 60_000); await assert.rejects(() => store.completePasswordReset("invalid", "new admin password", 2_000), /invalid or expired/); await assert.rejects(() => store.completePasswordReset(token, "new admin password", row.expires_at), /invalid or expired/); await store.completePasswordReset(token, "new admin password", 2_000); assert.equal(await store.verifyAdmin("new admin password"), true); assert.equal(await store.verifyAdmin("old admin password"), false); assert.ok(store.sessionRecord(adminSession).revoked_at); assert.equal(store.sessionRecord(childSession).revoked_at, null); await assert.rejects(() => store.completePasswordReset(token, "another admin password", 3_000), /invalid or expired/); });

test("Additional Access requires normalized unique email while legacy profiles remain visible", async (t) => { const store = makeStore(t); await assert.rejects(() => store.createChild({ displayName: "No email", password: "temporary password" }), /valid email/); await assert.rejects(() => store.createChild({ displayName: "Bad email", email: "bad address", password: "temporary password" }), /valid email/); const created = await store.createChild({ displayName: "Valid", email: " Person@Example.com ", password: "temporary password" }); assert.equal(created.email, "person@example.com"); await assert.rejects(() => store.createChild({ displayName: "Duplicate", email: "PERSON@example.com", password: "temporary password" }), /already uses/); const now = new Date().toISOString(); store.db.prepare("INSERT INTO jarvis_child_profiles (id, display_name, email, password_hash, enabled, permissions_json, session_limit_minutes, created_at, updated_at) VALUES (?, ?, NULL, ?, 1, '{}', 0, ?, ?)").run("legacy_profile", "Legacy", await hashPassword("temporary password"), now, now); const legacy = store.getChild("legacy_profile"); assert.equal(legacy.emailRequired, true); store.updateChild("legacy_profile", { enabled: false }); assert.throws(() => store.updateChild("legacy_profile", { enabled: true }), /valid email/); });

test("Child identity requires name and email before access is configured", async (t) => { const store = makeStore(t); await assert.rejects(() => store.setChildPassword("child password", { displayName: "Child" }), /valid email/); const child = await store.setChildPassword("child password", { displayName: "Child User", email: "child@example.com" }); assert.equal(child.displayName, "Child User"); assert.equal(child.email, "child@example.com"); });
