"use strict";
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { DatabaseSync } = require("node:sqlite");
const { AccessControlStore, DEFAULT_CHILD_PERMISSIONS, OWNER_PERMISSIONS, publicSession, sessionIdentity } = require("./accessControl");
const { requiredPermission } = require("./securityAccess");
function makeStore(t) { const file = path.join(os.tmpdir(), `jarvis-access-${crypto.randomUUID()}.sqlite`); const db = new DatabaseSync(file); const store = new AccessControlStore({ db }); store.open(); t.after(() => { db.close(); fs.rmSync(file, { force: true }); }); return store; }

test("security is disabled and primary access remains available until explicit setup", (t) => { const store = makeStore(t); assert.deepEqual(store.publicSettings(), { enabled: false, recoveryRequired: false, autoLockMinutes: 0 }); assert.equal(sessionIdentity({ session: {} }), null); });
test("a malformed persisted access record requires explicit owner recovery", async (t) => { const store = makeStore(t); store.db.prepare("INSERT INTO jarvis_security_settings (id, admin_password_hash, auto_lock_minutes, updated_at) VALUES (1, ?, 15, ?)").run("not-a-valid-hash", new Date().toISOString()); assert.equal(store.securityState(), "recovery_required"); assert.equal(store.publicSettings().recoveryRequired, true); await assert.rejects(() => store.setup("replacement safe password"), /recovery/); await store.recover("replacement safe password"); assert.equal(await store.verifyAdmin("replacement safe password"), true); });
test("owner setup uses a salted scrypt hash and exposes no hash", async (t) => { const store = makeStore(t); await store.setup("correct horse battery staple", 15); assert.equal(await store.verifyAdmin("correct horse battery staple"), true); assert.equal(await store.verifyAdmin("incorrect"), false); assert.deepEqual(store.publicSettings(), { enabled: true, recoveryRequired: false, autoLockMinutes: 15 }); assert.doesNotMatch(JSON.stringify(store.publicSettings()), /scrypt|horse/i); });
test("child profiles default to no permissions, respect disablement, and use bounded session expiry", async (t) => { const store = makeStore(t); await store.setup("correct horse battery staple"); const child = await store.createChild({ displayName: "Workflow user", password: "another safe password", sessionLimitMinutes: 15 }); assert.deepEqual(child.permissions, DEFAULT_CHILD_PERMISSIONS); assert.equal(Boolean(await store.verifyChild(child.id, "another safe password")), true); store.updateChild(child.id, { enabled: false }); assert.equal(await store.verifyChild(child.id, "another safe password"), null); const expiresAt = Date.now() + 1000; assert.equal(sessionIdentity({ session: { jarvisAuth: { role: "child", expiresAt } } }, expiresAt - 1).role, "child"); assert.equal(sessionIdentity({ session: { jarvisAuth: { role: "child", expiresAt } } }, expiresAt), null); });
test("public session grants full owner permissions and route policy is explicit", () => { const owner = publicSession({ session: { jarvisAuth: { role: "owner", displayName: "Owner" } } }); assert.deepEqual(owner.permissions, OWNER_PERMISSIONS); assert.equal(requiredPermission({ path: "/api/workflows", method: "GET" }), "view_workflow"); assert.equal(requiredPermission({ path: "/api/workflows", method: "POST" }), "edit_workflow"); assert.equal(requiredPermission({ path: "/api/workflow-executions/run", method: "POST" }), "run_workflow"); assert.equal(requiredPermission({ path: "/api/facebook/credentials", method: "POST" }), "publish_facebook"); assert.equal(requiredPermission({ path: "/api/google/credentials", method: "GET" }), "storage"); assert.equal(requiredPermission({ path: "/api/google/auth/start", method: "GET" }), "storage_modify"); assert.equal(requiredPermission({ path: "/api/ai/prepare-content", method: "POST" }), "run_workflow"); assert.equal(requiredPermission({ path: "/api/health", method: "GET" }), null); });
