
"use strict";
const { FacebookControlError } = require("./facebookControlStore");
function safe(res, error, logger) { if (error instanceof FacebookControlError) return res.status(400).json({ error: error.message, code: error.code }); logger?.error?.("Facebook Control operation failed safely."); return res.status(500).json({ error: "Facebook Control operation could not be completed." }); }
function registerFacebookControlRoutes(app, { store, workspaceForRequest = () => ({ ownerType: "admin", ownerId: "primary" }), facebookCredentialStore = null, logger = console } = {}) {
  if (!store) throw new Error("store is required");
  const workspace = (req, res) => { const owner = workspaceForRequest(req); if (!owner) { res.status(401).json({ error: "Authentication is required." }); return null; } return owner; };
  app.get("/api/facebook/control", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { return res.json(store.list(owner)); } catch (error) { return safe(res, error, logger); } });
  app.get("/api/facebook/performance", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { return res.json(store.list(owner)); } catch (error) { return safe(res, error, logger); } });
  app.post("/api/facebook/team-members", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { return res.status(201).json(store.createTeam(req.body, owner)); } catch (error) { return safe(res, error, logger); } });
  app.put("/api/facebook/team-members/:teamId", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { const team = store.updateTeam(req.params.teamId, req.body, owner); return team ? res.json(team) : res.status(404).json({ error: "Team member not found." }); } catch (error) { return safe(res, error, logger); } });
  app.post("/api/facebook/pages", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { return res.status(201).json(store.createPage(req.body, owner)); } catch (error) { return safe(res, error, logger); } });
  app.put("/api/facebook/pages/:pageId", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { const page = store.updatePage(req.params.pageId, req.body, owner); return page ? res.json(page) : res.status(404).json({ error: "Facebook Page record not found." }); } catch (error) { return safe(res, error, logger); } });
  app.delete("/api/facebook/pages/:pageId", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { return store.deletePage(req.params.pageId, owner) ? res.json({ ok: true, id: req.params.pageId }) : res.status(404).json({ error: "Facebook Page record not found." }); } catch (error) { return safe(res, error, logger); } });
  app.post("/api/facebook/pages/:pageId/test-connection", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { const data = store.list(owner); const page = data.pages.find((item) => item.id === req.params.pageId); if (!page) return res.status(404).json({ error: "Facebook Page record not found." }); if (!page.credentialId) return res.json({ ok: false, status: "connection_required", message: "Data connection required. Select an existing Facebook credential before live metrics can sync." }); if (facebookCredentialStore && !facebookCredentialStore.get(page.credentialId, { owner })) return res.status(404).json({ ok: false, status: "credential_not_found", message: "Selected Facebook credential was not found." }); return res.json({ ok: true, status: "connected", message: "Credential record is available. Live metric sync can use the server-side Meta integration." }); } catch (error) { return safe(res, error, logger); } });
  app.put("/api/facebook/sync-settings", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { return res.json(store.updateSync(req.body, owner)); } catch (error) { return safe(res, error, logger); } });
  app.post("/api/facebook/sync", (req, res) => { const owner = workspace(req, res); if (!owner) return; try { const sync = store.markSync(owner); return res.json({ ...store.list(owner), sync, status: "queued", message: "Refresh recorded. Live Meta metric fetching requires connected page permissions." }); } catch (error) { return safe(res, error, logger); } });
}
module.exports = { registerFacebookControlRoutes };
