function makeFacebookPopupHtml({ status, message = "", credentialId = null, clientUrl }) {
  const payload = JSON.stringify({ type: "jarvis-facebook-oauth", status, message, credentialId }).replace(/</g, "\\u003c");
  const origin = JSON.stringify(new URL(clientUrl).origin);
  const safeMessage = String(message).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
  return `<!doctype html><html><head><meta charset="utf-8"><title>Corex Meta Connection</title></head><body style="background:#101719;color:#e9f6f8;font-family:Arial;display:grid;place-items:center;min-height:100vh"><main><h2>${status === "connected" ? "Meta account connected" : "Meta sign-in not completed"}</h2><p>${safeMessage}</p></main><script>(function(){const payload=${payload};if(window.opener&&!window.opener.closed){window.opener.postMessage(payload,${origin});setTimeout(()=>window.close(),450);return;}const url=new URL(${JSON.stringify(clientUrl)});url.searchParams.set('facebook_oauth',payload.status==='connected'?'connected':'error');if(payload.credentialId)url.searchParams.set('facebook_credential_id',payload.credentialId);window.location.replace(url.toString());})();</script></body></html>`;
}

function makeFacebookPageSelectorHtml({ selectionId, pages, clientUrl }) {
  const safeSelectionId = JSON.stringify(selectionId).replace(/</g, "\\u003c");
  const safePages = JSON.stringify(pages.map((page) => ({ id: String(page.id), name: String(page.name) }))).replace(/</g, "\\u003c");
  const origin = JSON.stringify(new URL(clientUrl).origin);
  return `<!doctype html><html><head><meta charset="utf-8"><title>Select Facebook Page</title></head><body style="background:#101719;color:#e9f6f8;font-family:Arial;display:grid;place-items:center;min-height:100vh"><main style="min-width:320px"><h2>Select Facebook Page</h2><p>Choose the Page for this Corex credential.</p><select id="page" style="width:100%;padding:10px"></select><button id="connect" style="margin-top:14px;padding:10px 16px">Connect Page</button><p id="status" role="status"></p></main><script>(function(){const selectionId=${safeSelectionId};const pages=${safePages};const select=document.getElementById('page');for(const page of pages){const option=document.createElement('option');option.value=page.id;option.textContent=page.name;select.appendChild(option);}document.getElementById('connect').onclick=async function(){this.disabled=true;document.getElementById('status').textContent='Connecting Page...';try{const response=await fetch('/api/facebook/auth/page-selection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selectionId,pageId:select.value})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Page connection failed.');const payload={type:'jarvis-facebook-oauth',status:'connected',message:result.pageName+' is connected to Corex.',credentialId:result.id};if(window.opener&&!window.opener.closed){window.opener.postMessage(payload,${origin});setTimeout(()=>window.close(),450);}else{location.replace(${JSON.stringify(clientUrl)}+'?facebook_oauth=connected&facebook_credential_id='+encodeURIComponent(result.id));}}catch(error){document.getElementById('status').textContent=error.message;this.disabled=false;}};})();</script></body></html>`;
}
module.exports = { makeFacebookPageSelectorHtml, makeFacebookPopupHtml };
