const test = require("node:test"), assert = require("node:assert/strict"), express = require("express");
const { DatabaseSync } = require("node:sqlite");
const { InstagramStore, ownerKey } = require("./instagramStore");
const { registerInstagramRoutes } = require("./instagramRoutes");
const { authorizeInstagramOwner } = require("./instagramAccess");
test("Instagram HTTP setup and OAuth isolate all roles and reject CSRF, foreign state, disabled users and secret disclosure", async t => {
  const app = express(), store = new InstagramStore(new DatabaseSync(":memory:"), "secret"); let enabled = true;
  const access = { securityState: () => "enabled", settings: () => ({ auth_version: 1 }), childAccount: () => ({ enabled, authVersion: 1, permissions: { run_workflow: true, manage_workflow_credentials: true } }), getChild: id => ({ enabled, permissions: { edit_workflow: id !== "denied", run_workflow: true } }) };
  app.use((req, res, next) => { const id = req.get("X-Test-User"); req.sessionID = id || "anonymous"; req.session = id ? { jarvisAuth: { role: id === "admin" ? "admin" : id === "child" ? "child" : "additional", profileId: id, authVersion: 1 } } : {}; next(); });
  const service = { exclusive: async (owner, action) => { authorizeInstagramOwner(access, owner); return action(() => {}); }, publishReel: async (request, owner) => ({ workspace: ownerKey(owner) }), publicMedia: async () => { throw Error("invalid"); } };
  registerInstagramRoutes(app, { getStore: () => store, getAccessStore: () => access, getService: () => service, clientUrl: "https://corex.test", api: { exchange: async config => ({ id: "123", name: "creator", revision: config.revision, accessToken: "private-token", expiresAt: Date.now() + 86400000 }) } });
  const server = app.listen(0, "127.0.0.1"); await new Promise(resolve => server.once("listening", resolve)); t.after(() => { server.close(); store.db.close(); });
  const base = `http://127.0.0.1:${server.address().port}/api/instagram`;
  const call = (route, user, body, origin = "https://corex.test") => fetch(base + route, { redirect: "manual", headers: { ...(user ? { "X-Test-User": user } : {}), Origin: origin, "X-Corex-Instagram": "1", "Content-Type": "application/json" }, ...(body === undefined ? {} : { method: "POST", body: JSON.stringify(body) }) });
  assert.equal((await call("/config")).status, 401); assert.equal((await call("/media/invalid")).status, 404); assert.equal((await call("/config", "denied")).status, 403);
  for (const user of ["admin", "child", "alice", "bob"]) assert.equal((await call("/config", user)).status, 200);
  const config = { appId: "12345", appSecret: "private-app-secret" };
  assert.equal((await call("/config", "alice", config, "https://evil.test")).status, 403);
  assert.equal((await call("/config", "alice", config)).status, 200);
  const a = await (await call("/config", "alice")).json(); assert.equal(a.configured, true); assert.doesNotMatch(JSON.stringify(a), /private-app-secret/);
  assert.equal((await (await call("/config", "bob")).json()).configured, false);
  const start = await (await call("/auth/start", "alice", {})).json(), url = new URL(start.url), callback = `/auth/callback?state=${url.searchParams.get("state")}&code=code`;
  assert.equal(url.searchParams.get("scope"), "instagram_business_basic,instagram_business_content_publish");
  assert.match((await call(callback, "bob")).headers.get("location"), /failed/);
  assert.match((await call(callback, "alice")).headers.get("location"), /connected/);
  assert.match((await call(callback, "alice")).headers.get("location"), /failed/);
  const connected = await (await call("/config", "alice")).json(); assert.equal(connected.connected, true); assert.doesNotMatch(JSON.stringify(connected), /private-token|accessToken|appSecret/);
  assert.equal((await (await call("/videos/publish", "alice", { ownerId: "bob" })).json()).workspace, "additional:alice");
  await call("/config", "alice", { appId: "12345", appSecret: "new-private-app-secret" }); assert.equal((await (await call("/config", "alice")).json()).connected, false);
  enabled = false; assert.equal((await call("/config", "alice")).status, 401);
});
