"use strict";
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const express = require("express");
const fs = require("node:fs");
const http = require("node:http");
const os = require("node:os");
const path = require("node:path");
const session = require("express-session");
const test = require("node:test");
const { DatabaseSync } = require("node:sqlite");
const { AccessControlStore } = require("./accessControl");
const { enforceSecurity, registerSecurityRoutes } = require("./securityAccess");
const { configureSessionProxy, sessionOptions } = require("./sessionConfig");

async function fixture(t, { productionProxy = false } = {}) { const file = path.join(os.tmpdir(), `jarvis-security-http-${crypto.randomUUID()}.sqlite`); const db = new DatabaseSync(file); const store = new AccessControlStore({ db }); store.open(); const app = express(); configureSessionProxy(app, productionProxy); app.use(express.json()); app.use(session(sessionOptions({ secret: "test only session secret", isProduction: productionProxy }))); app.use(enforceSecurity(() => store)); registerSecurityRoutes(app, () => store); app.get("/api/health", (_, res) => res.json({ ok: true })); app.all("/api/workflows", (_, res) => res.json({ ok: true })); const listener = http.createServer(app); await new Promise((resolve) => listener.listen(0, "127.0.0.1", resolve)); const base = `http://127.0.0.1:${listener.address().port}`; t.after(async () => { await new Promise((resolve) => listener.close(resolve)); db.close(); fs.rmSync(file, { force: true }); }); return { store, request: async (route, options = {}) => { const headers = { ...(options.headers || {}) }; if (productionProxy) headers["x-forwarded-proto"] ||= "https"; const response = await fetch(`${base}${route}`, { ...options, headers }); return { response, body: await response.json(), setCookie: response.headers.get("set-cookie") || "", cookie: response.headers.get("set-cookie")?.split(";")[0] }; } }; }

test("production forwarded HTTPS issues a secure session and preserves Admin API authentication", async (t) => { const { store, request } = await fixture(t, { productionProxy: true }); await store.setup("admin secure password", 0, "owner@example.test"); const login = await request("/api/security/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ role: "admin", password: "admin secure password" }) }); assert.equal(login.response.status, 200); assert.match(login.setCookie, /; Secure/i); assert.match(login.setCookie, /; HttpOnly/i); assert.match(login.setCookie, /; SameSite=Lax/i); const owner = await request("/api/security/owner-account", { headers: { cookie: login.cookie } }); assert.equal(owner.response.status, 200); assert.equal(owner.body.account.email, "owner@example.test"); });

test("Admin endpoints reject unauthenticated and Child sessions behind the production proxy", async (t) => { const { store, request } = await fixture(t, { productionProxy: true }); await store.setup("admin secure password", 0, "owner@example.test"); await store.setChildPassword("child secure password", { displayName: "Child", email: "child@example.test" }); assert.ok([401, 403].includes((await request("/api/security/sessions")).response.status)); const login = await request("/api/security/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ role: "child", password: "child secure password" }) }); assert.equal(login.response.status, 200); assert.equal((await request("/api/security/children", { headers: { cookie: login.cookie } })).response.status, 403); });

test("security HTTP routes fail open before setup and enforce owner and workflow-only sessions after setup", async (t) => { const { store, request } = await fixture(t); assert.equal((await request("/api/workflows")).response.status, 200); const setup = await request("/api/security/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: "primary temporary password", confirmPassword: "primary temporary password", email: "owner@example.test" }) }); assert.equal(setup.response.status, 201); assert.doesNotMatch(JSON.stringify(setup.body), /temporary password|scrypt/i); assert.equal((await request("/api/workflows")).response.status, 401); const ownerHeaders = { cookie: setup.cookie, "content-type": "application/json" }; const child = await request("/api/security/children", { method: "POST", headers: ownerHeaders, body: JSON.stringify({ displayName: "Workflow only", email: "workflow@example.test", password: "child temporary password", permissions: { view_workflow: true } }) }); assert.equal(child.response.status, 201); const login = await request("/api/security/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileId: child.body.id, password: "child temporary password" }) }); const childHeaders = { cookie: login.cookie }; assert.equal((await request("/api/workflows", { headers: childHeaders })).response.status, 200); assert.equal((await request("/api/workflows", { method: "POST", headers: childHeaders })).response.status, 403); store.updateChild(child.body.id, { enabled: false }); assert.equal((await request("/api/security/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileId: child.body.id, password: "child temporary password" }) })).response.status, 401); });
test("malformed owner data never turns an unauthenticated or child request into access", async (t) => { const { store, request } = await fixture(t); store.db.prepare("INSERT INTO jarvis_security_settings (id, admin_password_hash, auto_lock_minutes, updated_at) VALUES (1, ?, 0, ?)").run("broken", new Date().toISOString()); assert.equal((await request("/api/workflows")).response.status, 503); assert.equal((await request("/api/security/recover", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: "replacement password", confirmPassword: "replacement password" }) })).response.status, 403); });
test("absolute expiry and manual disable immediately invalidate an existing child session", async (t) => { const { store, request } = await fixture(t); const setup = await request("/api/security/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: "primary temporary password", confirmPassword: "primary temporary password", email: "owner@example.test" }) }); const ownerHeaders = { cookie: setup.cookie, "content-type": "application/json" }; const child = await request("/api/security/children", { method: "POST", headers: ownerHeaders, body: JSON.stringify({ displayName: "Temporary", email: "temporary@example.test", password: "child temporary password", durationValue: 7, durationUnit: "days", permissions: { view_workflow: true } }) }); assert.equal(child.response.status, 201); assert.equal(child.body.durationValue, 7); assert.ok(child.body.accessExpiresAt > Date.now()); const login = await request("/api/security/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileId: child.body.id, password: "child temporary password" }) }); assert.equal(login.response.status, 200); const childHeaders = { cookie: login.cookie }; assert.equal((await request("/api/workflows", { headers: childHeaders })).response.status, 200); store.updateChild(child.body.id, { enabled: false }); assert.equal((await request("/api/workflows", { headers: childHeaders })).response.status, 401); store.updateChild(child.body.id, { enabled: true }); store.db.prepare("UPDATE jarvis_child_profiles SET access_expires_at = ? WHERE id = ?").run(Date.now() - 1, child.body.id); assert.equal((await request("/api/workflows", { headers: childHeaders })).response.status, 401); });
test("tampered custom duration requests above one year are rejected", async (t) => { const { request } = await fixture(t); const setup = await request("/api/security/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: "primary temporary password", confirmPassword: "primary temporary password", email: "owner@example.test" }) }); const response = await request("/api/security/children", { method: "POST", headers: { cookie: setup.cookie, "content-type": "application/json" }, body: JSON.stringify({ displayName: "Too long", email: "toolong@example.test", password: "child temporary password", durationValue: 366, durationUnit: "days" }) }); assert.equal(response.response.status, 400); assert.match(response.body.error, /between 1 day and 1 year/); });

test("Admin and Child use separate passwords, permissions, and revocable server sessions", async (t) => {
  const { store, request } = await fixture(t); const json = { "content-type": "application/json" };
  const setup = await request("/api/security/setup", { method: "POST", headers: json, body: JSON.stringify({ password: "admin secure password", confirmPassword: "admin secure password", email: "owner@example.test" }) });
  assert.equal(setup.response.status, 201); assert.equal(setup.body.session.role, "admin");
  const admin = { cookie: setup.cookie, ...json };
  const configured = await request("/api/security/password/child", { method: "PUT", headers: admin, body: JSON.stringify({ displayName: "Child", email: "child@example.test", password: "child secure password", confirmPassword: "child secure password" }) });
  assert.equal(configured.response.status, 200); assert.equal(configured.body.account.enabled, true); assert.doesNotMatch(JSON.stringify(configured.body), /child secure password|scrypt/);
  const wrong = await request("/api/security/login", { method: "POST", headers: json, body: JSON.stringify({ role: "child", password: "incorrect password" }) }); assert.equal(wrong.response.status, 401);
  const login = await request("/api/security/login", { method: "POST", headers: json, body: JSON.stringify({ role: "child", password: "child secure password" }) }); assert.equal(login.response.status, 200); assert.equal(login.body.session.role, "child");
  const child = { cookie: login.cookie, ...json }; assert.equal((await request("/api/workflows", { headers: child })).response.status, 200); assert.equal((await request("/api/workflows", { method: "POST", headers: child })).response.status, 403); assert.equal((await request("/api/security/child-access", { headers: child })).response.status, 403);
  const sessions = await request("/api/security/sessions", { headers: admin }); const childSession = sessions.body.sessions.find((item) => item.role === "child" && item.active); assert.ok(childSession);
  assert.equal((await request(`/api/security/sessions/${childSession.id}/revoke`, { method: "POST", headers: admin })).response.status, 200); assert.equal((await request("/api/workflows", { headers: child })).response.status, 401);
  assert.match(store.db.prepare("SELECT password_hash FROM jarvis_child_account WHERE id = 1").get().password_hash, /^scrypt\$/);
});

test("disabled Child access rejects login and logout invalidates Admin session", async (t) => {
  const { request } = await fixture(t); const json = { "content-type": "application/json" }; const setup = await request("/api/security/setup", { method: "POST", headers: json, body: JSON.stringify({ password: "admin secure password", confirmPassword: "admin secure password", email: "owner@example.test" }) }); const admin = { cookie: setup.cookie, ...json };
  await request("/api/security/password/child", { method: "PUT", headers: admin, body: JSON.stringify({ displayName: "Child", email: "child@example.test", password: "child secure password", confirmPassword: "child secure password" }) }); await request("/api/security/child-access", { method: "PUT", headers: admin, body: JSON.stringify({ enabled: false }) });
  const disabled = await request("/api/security/login", { method: "POST", headers: json, body: JSON.stringify({ role: "child", password: "child secure password" }) }); assert.equal(disabled.response.status, 403); assert.match(disabled.body.error, /disabled/);
  assert.equal((await request("/api/security/logout", { method: "POST", headers: admin })).response.status, 200); assert.equal((await request("/api/workflows", { headers: admin })).response.status, 401);
});

test("only Admin can permanently remove Additional Access, revoke its sessions, and reuse its email", async (t) => {
  const { store, request } = await fixture(t); const json = { "content-type": "application/json" };
  const setup = await request("/api/security/setup", { method: "POST", headers: json, body: JSON.stringify({ password: "admin secure password", confirmPassword: "admin secure password", email: "owner@example.test" }) }); const admin = { cookie: setup.cookie, ...json };
  await request("/api/security/password/child", { method: "PUT", headers: admin, body: JSON.stringify({ displayName: "Child", email: "child@example.test", password: "child secure password", confirmPassword: "child secure password" }) });
  const profile = await request("/api/security/children", { method: "POST", headers: admin, body: JSON.stringify({ displayName: "Temporary", email: "reusable@example.test", password: "additional secure password", permissions: { view_workflow: true } }) });
  const childLogin = await request("/api/security/login", { method: "POST", headers: json, body: JSON.stringify({ role: "child", password: "child secure password" }) });
  const additionalLogin = await request("/api/security/login", { method: "POST", headers: json, body: JSON.stringify({ profileId: profile.body.id, password: "additional secure password" }) });
  assert.equal((await request(`/api/security/children/${profile.body.id}`, { method: "DELETE" })).response.status, 403);
  assert.equal((await request(`/api/security/children/${profile.body.id}`, { method: "DELETE", headers: { cookie: childLogin.cookie } })).response.status, 403);
  assert.equal((await request(`/api/security/children/${profile.body.id}`, { method: "DELETE", headers: { cookie: additionalLogin.cookie } })).response.status, 403);
  const activeSession = store.db.prepare("SELECT id FROM jarvis_auth_sessions WHERE role = 'additional' AND profile_id = ? AND revoked_at IS NULL").get(profile.body.id); assert.ok(activeSession);
  assert.equal((await request(`/api/security/children/${profile.body.id}`, { method: "DELETE", headers: admin })).response.status, 200);
  assert.equal(store.getChild(profile.body.id), null); assert.ok(store.sessionRecord(activeSession.id).revoked_at);
  const recreated = await request("/api/security/children", { method: "POST", headers: admin, body: JSON.stringify({ displayName: "Replacement", email: "reusable@example.test", password: "replacement secure password", permissions: {} }) });
  assert.equal(recreated.response.status, 201); assert.notEqual(recreated.body.id, profile.body.id);
});
