"use strict";
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const express = require("express");
const fs = require("node:fs");
const http = require("node:http");
const os = require("node:os");
const path = require("node:path");
const session = require("express-session");
const test = require("node:test");
const { DatabaseSync } = require("node:sqlite");
const { AccessControlStore } = require("./accessControl");
const { enforceSecurity, registerSecurityRoutes } = require("./securityAccess");

async function fixture(t) { const file = path.join(os.tmpdir(), `jarvis-security-http-${crypto.randomUUID()}.sqlite`); const db = new DatabaseSync(file); const store = new AccessControlStore({ db }); store.open(); const app = express(); app.use(express.json()); app.use(session({ secret: "test only session secret", resave: false, saveUninitialized: false })); app.use(enforceSecurity(() => store)); registerSecurityRoutes(app, () => store); app.get("/api/health", (_, res) => res.json({ ok: true })); app.all("/api/workflows", (_, res) => res.json({ ok: true })); const listener = http.createServer(app); await new Promise((resolve) => listener.listen(0, "127.0.0.1", resolve)); const base = `http://127.0.0.1:${listener.address().port}`; t.after(async () => { await new Promise((resolve) => listener.close(resolve)); db.close(); fs.rmSync(file, { force: true }); }); return { store, request: async (route, options = {}) => { const response = await fetch(`${base}${route}`, options); return { response, body: await response.json(), cookie: response.headers.get("set-cookie")?.split(";")[0] }; } }; }

test("security HTTP routes fail open before setup and enforce owner and workflow-only sessions after setup", async (t) => { const { store, request } = await fixture(t); assert.equal((await request("/api/workflows")).response.status, 200); const setup = await request("/api/security/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: "primary temporary password", confirmPassword: "primary temporary password" }) }); assert.equal(setup.response.status, 201); assert.doesNotMatch(JSON.stringify(setup.body), /temporary password|scrypt/i); assert.equal((await request("/api/workflows")).response.status, 401); const ownerHeaders = { cookie: setup.cookie, "content-type": "application/json" }; const child = await request("/api/security/children", { method: "POST", headers: ownerHeaders, body: JSON.stringify({ displayName: "Workflow only", password: "child temporary password", permissions: { view_workflow: true } }) }); assert.equal(child.response.status, 201); const login = await request("/api/security/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileId: child.body.id, password: "child temporary password" }) }); const childHeaders = { cookie: login.cookie }; assert.equal((await request("/api/workflows", { headers: childHeaders })).response.status, 200); assert.equal((await request("/api/workflows", { method: "POST", headers: childHeaders })).response.status, 403); store.updateChild(child.body.id, { enabled: false }); assert.equal((await request("/api/security/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileId: child.body.id, password: "child temporary password" }) })).response.status, 401); });
test("malformed owner data never turns an unauthenticated or child request into access", async (t) => { const { store, request } = await fixture(t); store.db.prepare("INSERT INTO jarvis_security_settings (id, admin_password_hash, auto_lock_minutes, updated_at) VALUES (1, ?, 0, ?)").run("broken", new Date().toISOString()); assert.equal((await request("/api/workflows")).response.status, 503); assert.equal((await request("/api/security/recover", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: "replacement password", confirmPassword: "replacement password" }) })).response.status, 403); });
test("absolute expiry and manual disable immediately invalidate an existing child session", async (t) => { const { store, request } = await fixture(t); const setup = await request("/api/security/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: "primary temporary password", confirmPassword: "primary temporary password" }) }); const ownerHeaders = { cookie: setup.cookie, "content-type": "application/json" }; const child = await request("/api/security/children", { method: "POST", headers: ownerHeaders, body: JSON.stringify({ displayName: "Temporary", password: "child temporary password", durationValue: 7, durationUnit: "days", permissions: { view_workflow: true } }) }); assert.equal(child.response.status, 201); assert.equal(child.body.durationValue, 7); assert.ok(child.body.accessExpiresAt > Date.now()); const login = await request("/api/security/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ profileId: child.body.id, password: "child temporary password" }) }); assert.equal(login.response.status, 200); const childHeaders = { cookie: login.cookie }; assert.equal((await request("/api/workflows", { headers: childHeaders })).response.status, 200); store.updateChild(child.body.id, { enabled: false }); assert.equal((await request("/api/workflows", { headers: childHeaders })).response.status, 401); store.updateChild(child.body.id, { enabled: true }); store.db.prepare("UPDATE jarvis_child_profiles SET access_expires_at = ? WHERE id = ?").run(Date.now() - 1, child.body.id); assert.equal((await request("/api/workflows", { headers: childHeaders })).response.status, 401); });
test("tampered custom duration requests above one year are rejected", async (t) => { const { request } = await fixture(t); const setup = await request("/api/security/setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password: "primary temporary password", confirmPassword: "primary temporary password" }) }); const response = await request("/api/security/children", { method: "POST", headers: { cookie: setup.cookie, "content-type": "application/json" }, body: JSON.stringify({ displayName: "Too long", password: "child temporary password", durationValue: 366, durationUnit: "days" }) }); assert.equal(response.response.status, 400); assert.match(response.body.error, /between 1 day and 1 year/); });
