"use strict";

const { ADMIN_PERMISSIONS, hasPermission, publicSession, sessionIdentity } = require("./accessControl");
const { createEmailDelivery } = require("./emailDelivery");
const failures = new Map(); const MAX_FAILURES = 5; const LOCK_MS = 60_000;
const resetRequests = new Map(); const RESET_WINDOW_MS = 15 * 60_000; const RESET_MAX = 3;
function denied(res, status, error) { return res.status(status).json({ status: status === 401 ? "locked" : "forbidden", error }); }
function loginKey(req, role) { return `${req.ip || req.socket?.remoteAddress || "unknown"}:${role || "unknown"}`; }
function loginBlocked(key, now = Date.now()) { const value = failures.get(key); if (!value) return false; if (value.lockedUntil > now) return true; if (value.lockedUntil) failures.delete(key); return false; }
function recordFailure(key, now = Date.now()) { const value = failures.get(key) || { count: 0, lockedUntil: 0 }; value.count += 1; if (value.count >= MAX_FAILURES) { value.count = 0; value.lockedUntil = now + LOCK_MS; } failures.set(key, value); }
function allowResetRequest(key, now = Date.now()) { const value = resetRequests.get(key); if (!value || now - value.startedAt >= RESET_WINDOW_MS) { resetRequests.set(key, { count: 1, startedAt: now }); return true; } if (value.count >= RESET_MAX) return false; value.count += 1; return true; }
const STORAGE_NODE_PERMISSIONS = Object.freeze({ "Search Files and Folders": "storage", "Download File": "storage", "Move File": "storage_modify", "Delete File": "storage_modify" });
function requiredPermissions(req) {
  const permissions = [];
  if (req.path === "/api/workflow-executions/run") {
    permissions.push("run_workflow");
    for (const node of Array.isArray(req.body?.nodes) ? req.body.nodes : []) { const permission = STORAGE_NODE_PERMISSIONS[node?.name]; if (permission) permissions.push(permission); }
    return [...new Set(permissions)];
  }
  if (req.path.startsWith("/api/workflows")) return req.method === "GET" ? "view_workflow" : req.method === "DELETE" ? "delete_workflow" : "edit_workflow";
  if (req.path.startsWith("/api/executions")) return req.method === "GET" ? "view_workflow" : "run_workflow";
  if (req.path.startsWith("/api/facebook/reels/publish")) return "publish_facebook";
  if (req.path.startsWith("/api/facebook/graph/")) return "view_facebook";
  if (req.path.startsWith("/api/facebook/auth/")) return "publish_facebook";
  if (req.path.startsWith("/api/facebook/credentials")) return req.method === "GET" ? "view_facebook" : "publish_facebook";
  if (req.path.startsWith("/api/google/auth/")) return "storage_modify";
  if (req.path.startsWith("/api/google/credentials")) return req.method === "GET" ? "storage" : "storage_modify";
  if (req.path.startsWith("/api/google/drive/")) return ["move", "delete"].some((part) => req.path.endsWith(`/${part}`)) ? "storage_modify" : "storage";
  if (req.path === "/api/ai/prepare-content") return "run_workflow";
  if (req.path.startsWith("/api/conversation") || req.path.startsWith("/api/agent/")) return "conversation";
  return null;
}
function requiredPermission(req) { const value = requiredPermissions(req); return Array.isArray(value) ? value[0] || null : value; }
function enforceSecurity(getStore) { return (req, res, next) => { const store = getStore(); if (!store || req.path.startsWith("/api/security") || req.path === "/api/health" || store.securityState() === "disabled") return next(); if (store.securityState() === "recovery_required") return denied(res, 503, "Security recovery is required."); const required = requiredPermissions(req); const permissions = Array.isArray(required) ? required : required ? [required] : []; if (!permissions.length) return next(); const identity = sessionIdentity(req, Date.now(), store); if (!identity) return denied(res, 401, "Jarvis is locked. Authenticate to continue."); if (permissions.some((permission) => !hasPermission(req, permission, store))) return denied(res, 403, "This session does not have permission for that action."); store.touchSession(identity.sessionId); return next(); }; }
function establishSession(req, res, store, identity, status = 200) { const sessionId = store.createSession(identity.role, { profileId: identity.profileId, authVersion: identity.authVersion }); req.session.regenerate((error) => { if (error) return denied(res, 500, "Could not start a secure session."); req.session.jarvisAuth = { ...identity, sessionId }; return req.session.save(() => res.status(status).json({ security: store.publicSettings(), session: publicSession(req, store) })); }); }
function registerSecurityRoutes(app, getStore, emailDelivery = createEmailDelivery()) {
  const admin = (req, res) => { const store = getStore(); return ["admin", "owner"].includes(sessionIdentity(req, Date.now(), store)?.role) || (denied(res, 403, "Admin access is required."), false); };
  app.get("/api/security/status", (req, res) => { const store = getStore(); const security = store?.publicSettings() || { enabled: false, recoveryRequired: false, autoLockMinutes: 0 }; const session = security.enabled ? publicSession(req, store) : security.recoveryRequired ? null : { role: "admin", displayName: "Admin", permissions: ADMIN_PERMISSIONS, expiresAt: null }; return res.json({ security, session, childAvailable: Boolean(store?.childAccount()?.enabled), additionalProfilesAvailable: Boolean(store?.listChildren().some((profile) => profile.enabled && (!profile.accessExpiresAt || Date.now() < profile.accessExpiresAt))) }); });
  app.get("/api/security/public-profiles", (req, res) => { const store = getStore(); const now = Date.now(); return res.json({ profiles: store?.listChildren().filter((profile) => profile.enabled && (!profile.accessExpiresAt || now < profile.accessExpiresAt)).map(({ id, displayName }) => ({ id, displayName })) || [] }); });
  app.post("/api/security/setup", async (req, res) => { const store = getStore(); if (!store) return denied(res, 503, "Security is not ready."); if (req.body?.password !== req.body?.confirmPassword) return res.status(400).json({ error: "Passwords do not match." }); try { await store.setup(req.body?.password, req.body?.autoLockMinutes, req.body?.email); console.info("Jarvis security event: admin setup completed."); return establishSession(req, res, store, { role: "admin", displayName: "Admin", permissions: ADMIN_PERMISSIONS, authVersion: store.settings().auth_version }, 201); } catch (error) { return res.status(400).json({ error: error.message || "Security setup could not be completed." }); } });
  app.post("/api/security/recover", async (req, res) => { const store = getStore(); const secret = process.env.JARVIS_SECURITY_RECOVERY_SECRET; if (!store || !secret || req.get("x-jarvis-recovery-secret") !== secret) return denied(res, 403, "Admin recovery authorization is required."); if (req.body?.password !== req.body?.confirmPassword) return res.status(400).json({ error: "Passwords do not match." }); try { await store.recover(req.body?.password, req.body?.autoLockMinutes); return res.json({ security: store.publicSettings() }); } catch (error) { return res.status(400).json({ error: error.message || "Security recovery could not be completed." }); } });
  app.post("/api/security/login", async (req, res) => { const store = getStore(); if (!store?.publicSettings().enabled) return res.status(409).json({ error: "Security is not configured." }); const role = String(req.body?.role || (req.body?.profileId ? "additional" : "admin")).toLowerCase(); const key = loginKey(req, role); if (loginBlocked(key)) return res.status(429).json({ error: "Too many attempts. Try again in one minute." }); let identity = null; if (role === "admin" && await store.verifyAdmin(req.body?.password)) identity = { role: "admin", displayName: "Admin", permissions: ADMIN_PERMISSIONS, authVersion: store.settings().auth_version }; else if (role === "child") { const child = await store.verifyRoleChild(req.body?.password); if (child) identity = { role: "child", displayName: "Child", permissions: child.permissions, authVersion: child.authVersion }; else if (store.childAccount() && !store.childAccount().enabled) return res.status(403).json({ error: "Child access is currently disabled." }); } else if (role === "additional" && req.body?.profileId) { const profile = await store.verifyChild(req.body.profileId, req.body?.password); if (profile) identity = { role: "additional", profileId: profile.id, displayName: profile.displayName, permissions: profile.permissions, authVersion: 1, expiresAt: profile.accessExpiresAt || (profile.sessionLimitMinutes ? Date.now() + profile.sessionLimitMinutes * 60_000 : null) }; } if (!identity) { recordFailure(key); console.warn(`Jarvis security event: failed ${role} login.`); return denied(res, 401, "Incorrect password."); } failures.delete(key); console.info(`Jarvis security event: ${role} login.`); return establishSession(req, res, store, identity); });
  app.post("/api/security/logout", (req, res) => { const store = getStore(); const identity = sessionIdentity(req, Date.now(), store); if (identity) store.revokeSession(identity.sessionId); req.session.destroy(() => { res.clearCookie("connect.sid"); console.info("Jarvis security event: logout."); res.json({ ok: true }); }); });
  app.post("/api/security/lock", (req, res) => { const store = getStore(); const identity = sessionIdentity(req, Date.now(), store); if (identity) store.revokeSession(identity.sessionId); req.session.destroy(() => { res.clearCookie("connect.sid"); res.json({ ok: true }); }); });
  app.post("/api/security/password-reset/request", async (req, res) => { const message = "If this email matches the Owner account, recovery instructions have been sent."; const key = `${req.ip || req.socket?.remoteAddress || "unknown"}:${String(req.body?.email || "").trim().toLowerCase()}`; if (!allowResetRequest(key)) return res.json({ message }); try { const store = getStore(); const token = store?.createPasswordReset(req.body?.email); if (token) { console.info("Jarvis security event: password reset requested."); await emailDelivery.sendAdminReset(store.ownerAccount().email, token); } } catch { /* Public response must not disclose account existence or delivery state. */ } return res.json({ message }); });
  app.post("/api/security/password-reset/complete", async (req, res) => { if (!allowResetRequest(`complete:${req.ip || req.socket?.remoteAddress || "unknown"}`)) return res.status(429).json({ error: "Too many reset attempts. Try again later." }); if (req.body?.password !== req.body?.confirmPassword) return res.status(400).json({ error: "Passwords do not match." }); try { await getStore().completePasswordReset(req.body?.token, req.body?.password); console.info("Jarvis security event: password reset completed."); return res.json({ ok: true, reauthenticate: true }); } catch (error) { return res.status(400).json({ error: error.message || "This reset link is invalid or expired." }); } });
  app.get("/api/security/owner-account", (req, res) => admin(req, res) && res.json({ account: getStore().ownerAccount(), emailDeliveryConfigured: emailDelivery.configured }));
  app.put("/api/security/owner-email", async (req, res) => { if (!admin(req, res)) return; try { const account = await getStore().updateOwnerEmail(req.body?.currentPassword, req.body?.email); console.info("Jarvis security event: Admin email changed."); return res.json({ account }); } catch (error) { return res.status(400).json({ error: error.message }); } });
  app.get("/api/security/child-access", (req, res) => admin(req, res) && res.json({ account: getStore().childAccount() }));
  app.put("/api/security/child-access", (req, res) => { if (!admin(req, res)) return; try { const account = getStore().updateChildAccount(req.body || {}); console.info("Jarvis security event: child access configuration changed."); return res.json({ account }); } catch (error) { return res.status(400).json({ error: error.message }); } });
  app.put("/api/security/password/admin", async (req, res) => { if (!admin(req, res)) return; if (req.body?.password !== req.body?.confirmPassword) return res.status(400).json({ error: "Passwords do not match." }); try { await getStore().changeAdminPassword(req.body?.currentPassword, req.body?.password); console.info("Jarvis security event: admin password changed."); return req.session.destroy(() => res.json({ reauthenticate: true })); } catch (error) { return res.status(400).json({ error: error.message }); } });
  app.put("/api/security/password/child", async (req, res) => { if (!admin(req, res)) return; if (req.body?.password !== req.body?.confirmPassword) return res.status(400).json({ error: "Passwords do not match." }); try { return res.json({ account: await getStore().setChildPassword(req.body?.password, { displayName: req.body?.displayName, email: req.body?.email }) }); } catch (error) { return res.status(400).json({ error: error.message }); } });
  app.get("/api/security/sessions", (req, res) => admin(req, res) && res.json({ sessions: getStore().listSessions() }));
  app.post("/api/security/sessions/:id/revoke", (req, res) => { if (!admin(req, res)) return; getStore().revokeSession(req.params.id); console.info("Jarvis security event: session revoked."); return res.json({ ok: true }); });
  app.get("/api/security/children", (req, res) => admin(req, res) && res.json({ profiles: getStore().listChildren() }));
  app.post("/api/security/children", async (req, res) => { if (!admin(req, res)) return; try { return res.status(201).json(await getStore().createChild(req.body || {})); } catch (error) { return res.status(400).json({ error: error.message }); } });
  app.patch("/api/security/children/:id", (req, res) => { if (!admin(req, res)) return; try { const profile = getStore().updateChild(req.params.id, req.body || {}); return profile ? res.json(profile) : res.status(404).json({ error: "Profile not found." }); } catch (error) { return res.status(400).json({ error: error.message }); } });
  app.delete("/api/security/children/:id", (req, res) => { if (!admin(req, res)) return; const deleted = getStore().deleteChild(req.params.id); if (!deleted) return res.status(404).json({ error: "Profile not found." }); console.info("Jarvis security event: Additional Access profile removed."); return res.json({ ok: true }); });
}
module.exports = { STORAGE_NODE_PERMISSIONS, allowResetRequest, enforceSecurity, loginBlocked, recordFailure, registerSecurityRoutes, requiredPermission, requiredPermissions };
