const assert = require("node:assert/strict"); const test = require("node:test"); const { createWorkflowExecutor, resolveExpression } = require("./workflowExecutor");
const nodes = [{ id: "t", name: "Schedule Trigger", config: {} }, { id: "s", name: "Search Files and Folders", config: { credentialId: "g", query: "q" } }, { id: "l", name: "Limit", config: { maxItems: 1 } }]; const links = [{ source: "t", target: "s" }, { source: "s", target: "l" }];
function services(calls = []) { return { google: { searchFiles: async () => { calls.push("search"); return [{ id: "file_1" }, { id: "file_2" }]; }, downloadFile: async () => ({}), moveFile: async () => ({ status: "moved" }) }, facebook: { graphRequest: async () => ({}), publishReel: async () => ({ success: true, status: "published" }) }, youtube: { uploadVideo: async () => ({ success: true, videoId: "youtube-1" }) }, openAI: { prepare: async () => ({}) } }; }
test("executor runs a validated linear workflow deterministically", async () => { const calls = []; const result = await createWorkflowExecutor({ executionServices: services(calls), createExecutionId: () => "exec_1" }).execute({ workflowId: "w", nodes, connections: links }); assert.equal(result.status, "success"); assert.deepEqual(calls, ["search"]); assert.deepEqual(result.nodes.map((n) => n.nodeId), ["t", "s", "l"]); });
test("executor rejects invalid topology before provider calls", async () => { const calls = []; await assert.rejects(createWorkflowExecutor({ executionServices: services(calls) }).execute({ workflowId: "w", nodes, connections: [...links, { source: "s", target: "s" }] }), /self connections/); assert.deepEqual(calls, []); });
test("executor supports bounded fan-out and isolates failed siblings", async () => { const fan = [{ id: "t", name: "Schedule Trigger", config: {} }, ...[1,2,3,4,5].map((n) => ({ id: `s${n}`, name: "Search Files and Folders", config: { credentialId: "g", query: String(n) } }))]; let active = 0, max = 0; const svc = services(); svc.google.searchFiles = async (request) => { active++; max = Math.max(max, active); await new Promise((r) => setTimeout(r, 2)); active--; if (request.query === "2") throw new Error("fail"); return []; }; const result = await createWorkflowExecutor({ executionServices: svc }).execute({ workflowId: "f", nodes: fan, connections: fan.slice(1).map((n) => ({ source: "t", target: n.id })) }); assert.equal(result.status, "error"); assert.ok(max <= 4); assert.equal(result.branches.filter((b) => b.status === "success").length, 4); });
test("safe expressions resolve without eval", () => { assert.equal(resolveExpression("{{ $json.sourceFileId }}", { sourceFileId: "x" }), "x"); assert.equal(resolveExpression("id={{ $json.id }}", { id: "x" }), "id=x"); });
test("Search envelope feeds Limit first items and Download with the selected file ID", async () => { const calls = []; const workflow = [...nodes.map((node) => node.id === "l" ? { ...node, config: { ...node.config, keep: "First Items" } } : node), { id: "d", name: "Download File", config: { credentialId: "g", fileId: "{{ $json.id }}", binaryProperty: "data" } }]; const svc = services(calls); svc.google.searchFiles = async () => ({ status: "success", credentialId: "g", count: 5, files: [{ id: "file-1", name: "one.mp4", mimeType: "video/mp4" }, { id: "file-2", name: "two.mp4", mimeType: "video/mp4" }] }); svc.google.downloadFile = async (request) => { calls.push(["download", request.fileId]); return { id: request.fileId }; }; const result = await createWorkflowExecutor({ executionServices: svc }).execute({ workflowId: "search-limit-download", nodes: workflow, connections: [...links, { source: "l", target: "d" }] }); assert.equal(result.status, "success"); assert.deepEqual(calls, [["download", "file-1"]]); assert.deepEqual(result.nodes.find((node) => node.nodeId === "l").output, [{ id: "file-1", name: "one.mp4", mimeType: "video/mp4" }]); });
test("empty Search envelope reaches no per-item provider operation", async () => { const calls = []; const workflow = [...nodes, { id: "d", name: "Download File", config: { credentialId: "g", fileId: "{{ $json.id }}" } }, { id: "f", name: "Facebook Graph API", config: { operation: "Publish Reel", credentialId: "f" } }, { id: "m", name: "Move File", config: { credentialId: "g", fileId: "{{ $json.sourceFileId }}", destinationFolderId: "done" } }]; const svc = services(calls); svc.google.searchFiles = async () => ({ status: "success", credentialId: "g", count: 0, files: [] }); svc.google.downloadFile = async (request) => { calls.push(["download", request.fileId]); }; svc.facebook.publishReel = async () => { calls.push("facebook"); }; svc.google.moveFile = async () => { calls.push("move"); }; const result = await createWorkflowExecutor({ executionServices: svc }).execute({ workflowId: "empty-search", nodes: workflow, connections: [{ source: "t", target: "s" }, { source: "s", target: "l" }, { source: "l", target: "d" }, { source: "d", target: "f" }, { source: "f", target: "m" }] }); assert.equal(result.status, "success"); assert.deepEqual(calls, []); assert.deepEqual(result.nodes.find((node) => node.nodeId === "l").output, []); });
const itemPipelineNodes = [{ id: "t", name: "Schedule Trigger", config: {} }, { id: "s", name: "Search Files and Folders", config: { credentialId: "g" } }, { id: "l", name: "Limit", config: { maxItems: 1, keep: "First Items" } }, { id: "d", name: "Download File", config: { credentialId: "g", fileId: "{{ $json.id }}", binaryProperty: "data" } }, { id: "p", name: "Prepare Content", config: { fileName: "{{ $json.fileName }}" } }, { id: "f", name: "Facebook Graph API", config: { operation: "Publish Reel", credentialId: "f", title: "{{ $json.title }}", description: "{{ $json.socialCaption }}" } }, { id: "m", name: "Move File", config: { credentialId: "g", fileId: "{{ $json.sourceFileId }}", destinationFolderId: "done" } }];
const itemPipelineLinks = itemPipelineNodes.slice(0, -1).map((node, index) => ({ source: node.id, target: itemPipelineNodes[index + 1].id }));
function itemServices(calls) { const svc = services(calls); svc.google.searchFiles = async () => ({ status: "success", count: 2, files: [{ id: "file-1", name: "one.mp4", mimeType: "video/mp4" }, { id: "file-2", name: "two.mp4", mimeType: "video/mp4" }] }); svc.google.downloadFile = async (request) => { calls.push(["download", request.fileId]); return { fileId: request.fileId, fileName: "one.mp4", mimeType: "video/mp4", binary: { property: "data", referenceId: "bin-test", size: 123 } }; }; svc.openAI.prepare = async ({ body }) => { calls.push(["prepare", body.fileName]); return { title: "One title", caption: "One caption", hashtags: ["#one"], socialCaption: "One caption #one" }; }; svc.facebook.publishReel = async (request) => { calls.push(["facebook", request.title, request.description]); return { success: true, status: "published", sourceFileId: request.sourceFileId, sourceFileName: request.sourceFileName, videoId: "video-1" }; }; svc.google.moveFile = async (request) => { calls.push(["move", request.fileId]); return { success: true, status: "moved", fileId: request.fileId }; }; return svc; }
test("item pipeline prepares, publishes, and moves the selected Download item", async () => { const calls = []; const result = await createWorkflowExecutor({ executionServices: itemServices(calls) }).execute({ workflowId: "item-pipeline", nodes: itemPipelineNodes, connections: itemPipelineLinks }); assert.equal(result.status, "success"); assert.deepEqual(calls, [["download", "file-1"], ["prepare", "one.mp4"], ["facebook", "One title", "One caption #one"], ["move", "file-1"]]); const prepared = result.nodes.find((node) => node.nodeId === "p").output[0]; assert.equal(prepared.fileId, "file-1"); assert.equal(prepared.fileName, "one.mp4"); assert.equal(prepared.binary.referenceId, "bin-test"); assert.equal(prepared.title, "One title"); assert.equal(prepared.socialCaption, "One caption #one"); const published = result.nodes.find((node) => node.nodeId === "f").output[0]; assert.equal(published.sourceFileId, "file-1"); assert.equal(published.sourceFileName, "one.mp4"); });
test("item pipeline does not move after a safe Facebook publish failure", async () => { const calls = []; const svc = itemServices(calls); svc.facebook.publishReel = async () => { calls.push("facebook"); throw new Error("publish failed"); }; const result = await createWorkflowExecutor({ executionServices: svc, logger: { error() {} } }).execute({ workflowId: "publish-failure", nodes: itemPipelineNodes, connections: itemPipelineLinks }); assert.equal(result.status, "error"); assert.deepEqual(calls, [["download", "file-1"], ["prepare", "one.mp4"], "facebook"]); assert.equal(result.nodes.find((node) => node.nodeId === "f").status, "error"); assert.equal(result.nodes.some((node) => node.nodeId === "m"), false); });
test("manual and scheduled executor results preserve the same safe Facebook authorization diagnostic", async () => { for (const triggerMode of ["workflow", "schedule"]) { const svc = itemServices([]); svc.facebook.publishReel = async () => { const error = new Error("Cannot call API for app on behalf of user."); error.code = "meta_200"; error.diagnostic = { stage: "authorization", httpStatus: 400, metaCode: 200, metaSubcode: 2018065, metaType: "OAuthException", requiredPermission: "pages_manage_posts", traceId: "Trace_200", accessToken: "never-return", raw: "never-return" }; throw error; }; const result = await createWorkflowExecutor({ executionServices: svc, logger: { error() {} } }).execute({ workflowId: `auth-${triggerMode}`, nodes: itemPipelineNodes, connections: itemPipelineLinks, triggerMode }); const failure = result.nodes.find((node) => node.nodeId === "f"); assert.equal(failure.output.code, "meta_200"); assert.equal(failure.output.diagnostic.requiredPermission, "pages_manage_posts"); assert.equal(failure.output.diagnostic.traceId, "Trace_200"); assert.doesNotMatch(JSON.stringify(failure.output), /never-return|accessToken|"raw"/); } });
test("item pipeline keeps Publish success separate when Move fails", async () => { const calls = []; const svc = itemServices(calls); svc.google.moveFile = async (request) => { calls.push(["move", request.fileId]); throw new Error("move failed"); }; const result = await createWorkflowExecutor({ executionServices: svc, logger: { error() {} } }).execute({ workflowId: "move-failure", nodes: itemPipelineNodes, connections: itemPipelineLinks }); assert.equal(result.status, "error"); assert.equal(result.nodes.find((node) => node.nodeId === "f").status, "success"); assert.equal(result.nodes.find((node) => node.nodeId === "m").status, "error"); assert.deepEqual(calls.at(-1), ["move", "file-1"]); });
test("fan-out keeps item arrays branch-local and skips providers for an empty branch", async () => { const calls = []; const fanNodes = [{ id: "t", name: "Schedule Trigger", config: {} }, { id: "s1", name: "Search Files and Folders", config: { credentialId: "g", query: "one" } }, { id: "l1", name: "Limit", config: { maxItems: 1, keep: "First Items" } }, { id: "d1", name: "Download File", config: { credentialId: "g", fileId: "{{ $json.id }}" } }, { id: "s2", name: "Search Files and Folders", config: { credentialId: "g", query: "empty" } }, { id: "l2", name: "Limit", config: { maxItems: 1, keep: "First Items" } }, { id: "d2", name: "Download File", config: { credentialId: "g", fileId: "{{ $json.id }}" } }]; const svc = services(calls); svc.google.searchFiles = async ({ query }) => query === "one" ? { status: "success", files: [{ id: "branch-one" }] } : { status: "success", files: [] }; svc.google.downloadFile = async ({ fileId }) => { calls.push(fileId); return { fileId }; }; const result = await createWorkflowExecutor({ executionServices: svc }).execute({ workflowId: "fan-items", nodes: fanNodes, connections: [{ source: "t", target: "s1" }, { source: "s1", target: "l1" }, { source: "l1", target: "d1" }, { source: "t", target: "s2" }, { source: "s2", target: "l2" }, { source: "l2", target: "d2" }] }); assert.equal(result.status, "success"); assert.deepEqual(calls, ["branch-one"]); assert.equal(result.branches.length, 2); assert.deepEqual(result.nodes.find((node) => node.nodeId === "l2").output, []); });

const dualPublisherNodes = [...itemPipelineNodes.filter((node) => node.id !== "m"),
  { id: "y", name: "YouTube", config: { credentialId: "youtube", binaryProperty: "data", title: "{{ $json.title }}", description: "{{ $json.socialCaption }}", privacyStatus: "unlisted" } },
  itemPipelineNodes.find((node) => node.id === "m")];
const dualPublisherLinks = [{ source: "t", target: "s" }, { source: "s", target: "l" }, { source: "l", target: "d" }, { source: "d", target: "p" },
  { source: "p", target: "f" }, { source: "p", target: "y" }, { source: "f", target: "m" }, { source: "y", target: "m" }];

test("Facebook and YouTube publish the same prepared binary before one source move", async () => {
  const calls = []; const svc = itemServices(calls);
  svc.youtube = { uploadVideo: async (request) => { calls.push(["youtube", request.title, request.description, request.binary.referenceId]); return { success: true, videoId: "youtube-1", sourceFileId: request.sourceFileId, sourceFileName: request.sourceFileName, privacyStatus: request.privacyStatus }; } };
  const result = await createWorkflowExecutor({ executionServices: svc }).execute({ workflowId: "dual-publish", nodes: dualPublisherNodes, connections: dualPublisherLinks });
  assert.equal(result.status, "success"); assert.equal(calls.filter(([name]) => name === "move").length, 1);
  assert.deepEqual(calls.find(([name]) => name === "youtube"), ["youtube", "One title", "One caption #one", "bin-test"]);
  assert.deepEqual(calls.find(([name]) => name === "facebook").slice(1), ["One title", "One caption #one"]);
  assert.equal(result.nodes.find((node) => node.nodeId === "m").status, "success");
});

test("visual analysis failure stops both publishers and prevents Move File", async () => {
  const calls = []; const svc = itemServices(calls);
  svc.openAI.prepare = async ({ body }) => { calls.push(["prepare-visual", body.binary.referenceId]); const error = new Error("Visual analysis failed safely"); error.code = "visual_analysis_failed"; throw error; };
  svc.facebook.publishReel = async () => { calls.push(["facebook"]); return { success: true, status: "published" }; };
  svc.youtube = { uploadVideo: async () => { calls.push(["youtube"]); return { success: true, videoId: "youtube-1" }; } };
  svc.google.moveFile = async () => { calls.push(["move"]); return { success: true, status: "moved" }; };
  const result = await createWorkflowExecutor({ executionServices: svc, logger: { error() {} } }).execute({ workflowId: "visual-fail", nodes: dualPublisherNodes, connections: dualPublisherLinks });
  assert.equal(result.status, "error"); assert.deepEqual(calls, [["download", "file-1"], ["prepare-visual", "bin-test"]]);
  assert.equal(result.nodes.find((node) => node.nodeId === "p").status, "error");
  assert.equal(result.nodes.find((node) => node.nodeId === "m").status, "error");
});

for (const failedPublisher of ["facebook", "youtube"]) test(`${failedPublisher} failure prevents Move File and total success`, async () => {
  const calls = []; const svc = itemServices(calls);
  svc.youtube = { uploadVideo: async (request) => { calls.push(["youtube", request.sourceFileId]); if (failedPublisher === "youtube") { const error = new Error("YouTube failed safely"); error.code = "youtube_upload_failed"; throw error; } return { success: true, videoId: "youtube-1", sourceFileId: request.sourceFileId, sourceFileName: request.sourceFileName }; } };
  if (failedPublisher === "facebook") svc.facebook.publishReel = async () => { calls.push(["facebook"]); throw new Error("Facebook failed"); };
  const result = await createWorkflowExecutor({ executionServices: svc, logger: { error() {} } }).execute({ workflowId: `dual-${failedPublisher}-failure`, nodes: dualPublisherNodes, connections: dualPublisherLinks });
  assert.equal(result.status, "error"); assert.equal(calls.some(([name]) => name === "move"), false);
  assert.equal(result.nodes.find((node) => node.nodeId === "m").status, "error");
});
