"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { createWorkflowStore } = require("./workflowStore");

function fixture(name = "Workflow", extra = {}) { return { name, nodes: [{ id: "n1", config: { credentialId: "gcred_opaque" } }], connections: [], schedule: { rules: [] }, timezone: "Asia/Riyadh", ...extra }; }
function tempStore(t, dbPath = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-workflows-")), "workflows.sqlite3")) { const store = createWorkflowStore({ dbPath, now: (() => { let i = 0; return () => `2026-01-01T00:00:0${i++}.000Z`; })() }); t.after(() => { store.close(); fs.rmSync(path.dirname(dbPath), { recursive: true, force: true }); }); return { store, dbPath }; }

test("workflow store initializes idempotently and persists normalized definitions", (t) => { const { store, dbPath } = tempStore(t); const second = createWorkflowStore({ dbPath }); second.close(); const created = store.createWorkflow(fixture()); assert.match(created.id, /^wf_/); assert.equal(created.status, "DRAFT"); assert.deepEqual(created.nodes, fixture().nodes); assert.deepEqual(created.connections, []); assert.deepEqual(created.schedule, { rules: [] }); assert.equal(created.timezone, "Asia/Riyadh"); assert.deepEqual(store.getWorkflow(created.id), created); assert.equal(store.getWorkflow("wf_missing"), null); });
test("workflow store validates statuses, definitions, immutable fields, and secret-bearing keys", (t) => { const { store } = tempStore(t); assert.equal(store.createWorkflow(fixture("Active", { status: "ACTIVE" })).status, "ACTIVE"); assert.equal(store.createWorkflow(fixture("Paused", { status: "PAUSED" })).status, "PAUSED"); assert.throws(() => store.createWorkflow(fixture("Bad", { status: "RUNNING" })), /status/); assert.throws(() => store.createWorkflow(fixture("Bad", { nodes: {} })), /nodes/); assert.throws(() => store.createWorkflow(fixture("Bad", { connections: {} })), /connections/); assert.throws(() => store.createWorkflow(fixture("Secret", { nodes: [{ config: { accessToken: "not logged" } }] })), /secrets/); const saved = store.createWorkflow(fixture("Safe opaque")); assert.throws(() => store.updateWorkflow(saved.id, { id: "wf_replaced" }), /cannot be updated/); assert.throws(() => store.updateWorkflow(saved.id, { createdAt: "x" }), /cannot be updated/); });
test("workflow store persists opaque Google and Facebook credential IDs without resolving credentials", (t) => { const { store } = tempStore(t); const google = store.createWorkflow(fixture("Google", { nodes: [{ id: "search", config: { credentialId: "gcred_test123" } }] })); assert.equal(store.getWorkflow(google.id).nodes[0].config.credentialId, "gcred_test123"); const replaced = store.updateWorkflow(google.id, { nodes: [{ id: "search", config: { credentialId: "gcred_replacement" } }] }); assert.equal(replaced.nodes[0].config.credentialId, "gcred_replacement"); assert.equal(Object.hasOwn(replaced.nodes[0].config, "tokens"), false); const facebook = store.createWorkflow(fixture("Facebook", { nodes: [{ id: "facebook", name: "Facebook Graph API", config: { credentialId: "fcred_test123" } }] })); assert.equal(store.getWorkflow(facebook.id).nodes[0].config.credentialId, "fcred_test123"); });
test("workflow store rejects all secret-bearing key variants while allowing the existing opaque credential reference", (t) => { const { store } = tempStore(t); for (const key of ["accessToken", "REFRESH_TOKEN", "apiKey", "CLIENT-SECRET", "password", "Authorization"]) assert.throws(() => store.createWorkflow(fixture("Secret", { nodes: [{ config: { [key]: "do-not-return-secret" } }] })), /secrets/); const saved = store.createWorkflow(fixture("Opaque reference", { nodes: [{ config: { credentialId: "opaque_reference_only" } }] })); assert.equal(saved.nodes[0].config.credentialId, "opaque_reference_only"); });
test("workflow store lists, updates, deletes, and isolates 100 independent workflows", (t) => { const { store } = tempStore(t); const workflows = Array.from({ length: 100 }, (_, index) => store.createWorkflow(fixture(`Workflow ${index}`))); assert.equal(new Set(workflows.map((workflow) => workflow.id)).size, 100); const page = store.listWorkflows({ limit: 10, offset: 20 }); assert.equal(page.total, 100); assert.equal(page.items.length, 10); assert.equal(Object.hasOwn(page.items[0], "nodes"), false); const first = workflows[0], second = workflows[1]; const updated = store.updateWorkflow(first.id, { name: "Renamed", status: "ACTIVE", nodes: [{ id: "changed" }], lastRunAt: "2026-01-02T00:00:00.000Z", nextRunAt: "2026-01-03T00:00:00.000Z" }); assert.equal(updated.name, "Renamed"); assert.equal(updated.status, "ACTIVE"); assert.equal(updated.version, 2); assert.notEqual(updated.updatedAt, first.updatedAt); assert.deepEqual(store.getWorkflow(second.id).nodes, second.nodes); assert.equal(store.deleteWorkflow(first.id), true); assert.equal(store.getWorkflow(first.id), null); assert.equal(store.deleteWorkflow(first.id), false); assert.equal(store.listWorkflows({ limit: 100, offset: 0 }).total, 99); });
test("workflow store retains records after close and reopen", (t) => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-workflows-reopen-")); const dbPath = path.join(directory, "workflows.sqlite3"); const first = createWorkflowStore({ dbPath }); const created = first.createWorkflow(fixture("Persistent")); first.close(); const reopened = createWorkflowStore({ dbPath }); t.after(() => { reopened.close(); fs.rmSync(directory, { recursive: true, force: true }); }); assert.equal(reopened.getWorkflow(created.id).name, "Persistent"); });
