"use strict";

const assert = require("node:assert/strict");
const express = require("express");
const fs = require("node:fs");
const http = require("node:http");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { createWorkflowStore } = require("./workflowStore");
const { registerWorkflowRoutes } = require("./workflowRoutes");

function definition(name = "Workflow", extra = {}) { return { name, nodes: [{ id: "node", config: { credentialId: "gcred_opaque" } }], connections: [], schedule: { rules: [] }, timezone: "Asia/Riyadh", ...extra }; }
async function server(t) { const directory = fs.mkdtempSync(path.join(os.tmpdir(), "jarvis-workflow-routes-")); const store = createWorkflowStore({ dbPath: path.join(directory, "workflows.sqlite3") }); const app = express(); app.use(express.json()); registerWorkflowRoutes(app, { workflowStore: store, logger: { error() {} } }); const listener = http.createServer(app); await new Promise((resolve) => listener.listen(0, "127.0.0.1", resolve)); const base = `http://127.0.0.1:${listener.address().port}`; t.after(async () => { await new Promise((resolve) => listener.close(resolve)); store.close(); fs.rmSync(directory, { recursive: true, force: true }); }); return async (method, route, body) => { const response = await fetch(`${base}${route}`, { method, headers: body === undefined ? undefined : { "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); return { status: response.status, body: await response.json() }; }; }

test("workflow CRUD creates, reads, updates, and deletes safe workflow definitions", async (t) => { const request = await server(t); const created = await request("POST", "/api/workflows", definition()); assert.equal(created.status, 201); assert.match(created.body.id, /^wf_/); assert.equal(created.body.status, "DRAFT"); assert.deepEqual(created.body.nodes, definition().nodes); assert.deepEqual(created.body.connections, []); assert.deepEqual(created.body.schedule, { rules: [] }); assert.equal(created.body.timezone, "Asia/Riyadh"); for (const status of ["ACTIVE", "PAUSED"]) assert.equal((await request("POST", "/api/workflows", definition(status, { status }))).body.status, status); const read = await request("GET", `/api/workflows/${created.body.id}`); assert.equal(read.status, 200); assert.equal(Array.isArray(read.body.nodes), true); const updated = await request("PATCH", `/api/workflows/${created.body.id}`, { name: "Updated", status: "ACTIVE", nodes: [{ id: "updated" }], connections: [{ source: "a", target: "b" }], schedule: null, timezone: "UTC" }); assert.equal(updated.status, 200); assert.equal(updated.body.version, 2); assert.equal(updated.body.name, "Updated"); assert.equal(updated.body.timezone, "UTC"); assert.equal(updated.body.schedule, null); assert.equal((await request("DELETE", `/api/workflows/${created.body.id}`)).status, 200); assert.equal((await request("GET", `/api/workflows/${created.body.id}`)).status, 404); });
test("workflow CRUD rejects forged metadata, invalid definitions, secrets, and missing records safely", async (t) => { const request = await server(t); for (const body of [{ ...definition(), id: "wf_forged" }, { ...definition(), createdAt: "x" }, { ...definition(), version: 99 }, definition("Bad", { status: "RUNNING" }), definition("Secret", { nodes: [{ config: { accessToken: "value" } }] })]) { const result = await request("POST", "/api/workflows", body); assert.equal(result.status, 400); assert.equal(Object.values(result.body).join(" ").includes("value"), false); } const created = await request("POST", "/api/workflows", definition()); for (const body of [{ id: "wf_forged" }, { createdAt: "x" }, { version: 99 }, { lastRunAt: "x" }, { nextRunAt: "x" }, { status: "RUNNING" }, { nodes: [{ apiKey: "value" }] }]) assert.equal((await request("PATCH", `/api/workflows/${created.body.id}`, body)).status, 400); assert.equal((await request("GET", "/api/workflows/wf_bad")).status, 400); assert.equal((await request("PATCH", "/api/workflows/wf_abcdefgh", { name: "Missing" })).status, 404); assert.equal((await request("DELETE", "/api/workflows/wf_abcdefgh")).status, 404); });
test("workflow CRUD round-trips opaque credential IDs and safely rejects secret keys", async (t) => { const request = await server(t); const google = await request("POST", "/api/workflows", definition("Google", { nodes: [{ id: "search", config: { credentialId: "gcred_test123" } }] })); assert.equal(google.status, 201); assert.equal((await request("GET", `/api/workflows/${google.body.id}`)).body.nodes[0].config.credentialId, "gcred_test123"); const updated = await request("PATCH", `/api/workflows/${google.body.id}`, { nodes: [{ id: "search", config: { credentialId: "gcred_replacement" } }] }); assert.equal(updated.status, 200); assert.equal(updated.body.nodes[0].config.credentialId, "gcred_replacement"); assert.equal(Object.hasOwn(updated.body.nodes[0].config, "tokens"), false); const facebook = await request("POST", "/api/workflows", definition("Facebook", { nodes: [{ id: "facebook", name: "Facebook Graph API", config: { credentialId: "fcred_test123" } }] })); assert.equal(facebook.status, 201); assert.equal((await request("GET", `/api/workflows/${facebook.body.id}`)).body.nodes[0].config.credentialId, "fcred_test123"); const summary = await request("GET", "/api/workflows?limit=10"); assert.equal(Object.hasOwn(summary.body.workflows.find((workflow) => workflow.id === google.body.id), "nodes"), false); for (const key of ["accessToken", "refreshToken", "apiKey", "clientSecret", "password", "authorization", "ACCESS_TOKEN", "Client-Secret"]) { const secret = "do-not-return-secret"; const rejected = await request("POST", "/api/workflows", definition("Rejected", { nodes: [{ config: { [key]: secret } }] })); assert.equal(rejected.status, 400); assert.doesNotMatch(JSON.stringify(rejected.body), new RegExp(secret)); } });
test("workflow CRUD lists bounded summaries and keeps 100 workflows isolated", async (t) => { const request = await server(t); const created = []; for (let index = 0; index < 100; index += 1) { const result = await request("POST", "/api/workflows", definition(`Workflow ${index}`)); assert.equal(result.status, 201); created.push(result.body); } assert.equal(new Set(created.map((workflow) => workflow.id)).size, 100); const page = await request("GET", "/api/workflows?limit=10&offset=20"); assert.equal(page.status, 200); assert.equal(page.body.total, 100); assert.equal(page.body.workflows.length, 10); assert.equal(Object.hasOwn(page.body.workflows[0], "nodes"), false); assert.equal((await request("GET", "/api/workflows?limit=101")).status, 400); assert.equal((await request("GET", "/api/workflows?offset=-1")).status, 400); const first = created[0], second = created[1]; assert.equal((await request("PATCH", `/api/workflows/${first.id}`, { nodes: [{ id: "only-first" }] })).status, 200); assert.deepEqual((await request("GET", `/api/workflows/${second.id}`)).body.nodes, second.nodes); assert.equal((await request("DELETE", `/api/workflows/${first.id}`)).status, 200); assert.equal((await request("GET", "/api/workflows?limit=100")).body.total, 99); });
