
import { useEffect, useMemo, useState } from "react";
import { createFacebookPage, createFacebookTeam, deleteFacebookPage, getFacebookControl, refreshFacebookPages, testFacebookPageConnection, updateFacebookPage, updateFacebookSyncSettings } from "./facebookControlApi.js";

const EMPTY_PAGE = { pageUrl: "", pageName: "", pageId: "", teamMemberId: "", credentialId: "", status: "NEEDS_CONNECTION", notes: "" };

function fmt(value) { return value ? new Date(value).toLocaleString() : "Never"; }

export default function FacebookControl({ apiBaseUrl = "", credentials = [] }) {
  const [state, setState] = useState({ teams: [], pages: [], sync: { refreshIntervalMinutes: 5, lastSyncAt: null } });
  const [pageForm, setPageForm] = useState(EMPTY_PAGE);
  const [teamName, setTeamName] = useState("");
  const [editingPageId, setEditingPageId] = useState(null);
  const [notice, setNotice] = useState("");
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setState(await getFacebookControl(fetch, apiBaseUrl)); } catch (error) { setNotice(error.message); } finally { setLoading(false); } };
  useEffect(() => { let active = true; getFacebookControl(fetch, apiBaseUrl).then((data) => { if (active) setState(data); }).catch((error) => { if (active) setNotice(error.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [apiBaseUrl]);
  const pagesByTeam = useMemo(() => new Map(state.teams.map((team) => [team.id, state.pages.filter((page) => page.teamMemberId === team.id).length])), [state.teams, state.pages]);
  const saveTeam = async () => { if (!teamName.trim()) return; try { await createFacebookTeam(fetch, apiBaseUrl, { name: teamName.trim() }); setTeamName(""); await load(); setNotice("Team member saved."); } catch (error) { setNotice(error.message); } };
  const savePage = async (event) => { event.preventDefault(); try { if (editingPageId) await updateFacebookPage(fetch, apiBaseUrl, editingPageId, pageForm); else await createFacebookPage(fetch, apiBaseUrl, pageForm); setPageForm(EMPTY_PAGE); setEditingPageId(null); await load(); setNotice("Facebook Page saved."); } catch (error) { setNotice(error.message); } };
  const editPage = (page) => { setEditingPageId(page.id); setPageForm({ pageUrl: page.pageUrl, pageName: page.pageName, pageId: page.pageId || "", teamMemberId: page.teamMemberId || "", credentialId: page.credentialId || "", status: page.status, notes: page.notes || "" }); };
  const removePage = async (page) => { if (!window.confirm(`Remove Facebook Page record "${page.pageName}"?`)) return; try { await deleteFacebookPage(fetch, apiBaseUrl, page.id); await load(); setNotice("Facebook Page removed."); } catch (error) { setNotice(error.message); } };
  const testPage = async (page) => { try { const result = await testFacebookPageConnection(fetch, apiBaseUrl, page.id); setNotice(result.message || result.status); } catch (error) { setNotice(error.message); } };
  const updateInterval = async (event) => { try { const sync = await updateFacebookSyncSettings(fetch, apiBaseUrl, { refreshIntervalMinutes: Number(event.target.value) }); setState((current) => ({ ...current, sync })); setNotice("Refresh interval saved."); } catch (error) { setNotice(error.message); } };
  const refreshNow = async () => { try { const data = await refreshFacebookPages(fetch, apiBaseUrl); setState({ teams: data.teams, pages: data.pages, sync: data.sync }); setNotice(data.message || "Refresh queued."); } catch (error) { setNotice(error.message); } };
  return <section className="facebook-control-page">
    <header className="facebook-control-hero"><div><span>FACEBOOK CONTROL</span><h1>Facebook Pages & Team</h1><p>Register Facebook Pages, assign each page to a team member, and connect server-side Meta credentials when live metrics are available.</p></div><button type="button" onClick={refreshNow}>Refresh Now</button></header>
    {notice && <div className="facebook-control-notice" role="status">{notice}</div>}
    <div className="facebook-control-toolbar"><label>Facebook Refresh Interval<select value={state.sync.refreshIntervalMinutes} onChange={updateInterval}>{[1,5,15,30,60].map((value) => <option key={value} value={value}>{value} minute{value === 1 ? "" : "s"}</option>)}</select></label><span>Last updated: {fmt(state.sync.lastSyncAt)}</span></div>
    <div className="facebook-control-layout">
      <form className="facebook-control-card page-form" onSubmit={savePage}><h2>{editingPageId ? "Edit Facebook Page" : "+ Add Facebook Page"}</h2><label>Page URL<input value={pageForm.pageUrl} onChange={(event) => setPageForm({ ...pageForm, pageUrl: event.target.value })} placeholder="https://www.facebook.com/yourpage" /></label><label>Page Name<input value={pageForm.pageName} onChange={(event) => setPageForm({ ...pageForm, pageName: event.target.value })} /></label><label>Team Member<select value={pageForm.teamMemberId} onChange={(event) => setPageForm({ ...pageForm, teamMemberId: event.target.value })}><option value="">Unassigned</option>{state.teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>Page ID<input value={pageForm.pageId} onChange={(event) => setPageForm({ ...pageForm, pageId: event.target.value })} /></label><label>Credential<select value={pageForm.credentialId} onChange={(event) => setPageForm({ ...pageForm, credentialId: event.target.value })}><option value="">Data connection required</option>{credentials.map((credential) => <option key={credential.id} value={credential.id}>{credential.pageName || credential.accountName || credential.id}</option>)}</select></label><label>Status<select value={pageForm.status} onChange={(event) => setPageForm({ ...pageForm, status: event.target.value })}><option>ACTIVE</option><option>INACTIVE</option><option>NEEDS_CONNECTION</option><option>PAUSED</option></select></label><label>Notes<textarea rows="3" value={pageForm.notes} onChange={(event) => setPageForm({ ...pageForm, notes: event.target.value })} /></label><div className="facebook-control-actions"><button type="submit">Save</button><button type="button" onClick={() => { setEditingPageId(null); setPageForm(EMPTY_PAGE); }}>Clear</button></div></form>
      <aside className="facebook-control-card team-panel"><h2>Team Members</h2><div className="team-add-row"><input value={teamName} onChange={(event) => setTeamName(event.target.value)} placeholder="Add team member" /><button type="button" onClick={saveTeam}>Add</button></div>{state.teams.length ? state.teams.map((team) => <article key={team.id}><strong>{team.name}</strong><span>Pages: {pagesByTeam.get(team.id) || 0}</span></article>) : <p>No team members yet.</p>}</aside>
    </div>
    <section className="facebook-control-card page-list"><h2>Registered Facebook Pages</h2>{loading ? <p>Loading Facebook Pages...</p> : !state.pages.length ? <div className="facebook-empty-state"><strong>No Facebook Pages have been added yet.</strong><span>Add a page URL and assign it to a team member.</span></div> : <div className="facebook-control-table">{state.pages.map((page) => <article key={page.id}><div><strong>{page.pageName}</strong><a href={page.pageUrl} target="_blank" rel="noreferrer">Open Page</a></div><span>Manager: {page.teamMemberName}</span><span>Status: {page.status}</span><span>Data: {page.dataConnectionStatus === "connected" ? "Connected" : "Data connection required"}</span><span>Last sync: {fmt(page.lastSyncAt)}</span><div><button type="button" onClick={() => editPage(page)}>Edit</button><button type="button" onClick={() => testPage(page)}>Test Connection</button><button type="button" onClick={() => removePage(page)}>Remove</button></div></article>)}</div>}</section>
  </section>;
}
