import { createContext, useContext, useEffect, useState } from "react";

const API = import.meta.env.VITE_API_BASE_URL || (import.meta.env.DEV ? "http://localhost:3001" : "");
const AuthContext = createContext({ session: null, can: () => false, refresh: async () => {}, endSession: async () => {} });
async function request(path, options = {}) { const response = await fetch(`${API}${path}`, { credentials: "include", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Authentication request failed."); return data; }
// oxlint-disable-next-line react/only-export-components -- the hook and provider share one private context.
export function useJarvisAuth() { return useContext(AuthContext); }

export function JarvisAuthGate({ children }) {
  const resetToken = new URLSearchParams(window.location.search).get("reset_token") || "";
  const [status, setStatus] = useState(null); const [role, setRole] = useState("admin"); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [email, setEmail] = useState(""); const [profiles, setProfiles] = useState([]); const [profileId, setProfileId] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [forgot, setForgot] = useState(false); const [resetComplete, setResetComplete] = useState(false);
  const refresh = async () => { try { setStatus(await request("/api/security/status")); } catch (reason) { setError(reason.message); setStatus({ security: { enabled: true }, session: null }); } };
  useEffect(() => { void Promise.resolve().then(refresh); const listener = () => void refresh(); window.addEventListener("jarvis-auth-changed", listener); return () => window.removeEventListener("jarvis-auth-changed", listener); }, []);
  useEffect(() => { if (status?.additionalProfilesAvailable && !status.session) request("/api/security/public-profiles").then((data) => setProfiles(data.profiles || [])).catch(() => setProfiles([])); }, [status?.additionalProfilesAvailable, status?.session]);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { const data = status.security.enabled ? await request("/api/security/login", { method: "POST", body: JSON.stringify({ role, profileId: role === "additional" ? profileId : undefined, password }) }) : await request("/api/security/setup", { method: "POST", body: JSON.stringify({ email, password, confirmPassword }) }); setStatus(data); setPassword(""); setConfirmPassword(""); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  const sendReset = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { const data = await request("/api/security/password-reset/request", { method: "POST", body: JSON.stringify({ email }) }); setNotice(data.message); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  const completeReset = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await request("/api/security/password-reset/complete", { method: "POST", body: JSON.stringify({ token: resetToken, password, confirmPassword }) }); setResetComplete(true); window.history.replaceState({}, "", window.location.pathname); setNotice("Admin password reset. Sign in with the new password."); setPassword(""); setConfirmPassword(""); } catch (reason) { setError(reason.message); } finally { setBusy(false); } };
  const endSession = async (action = "logout") => { await request(`/api/security/${action}`, { method: "POST" }); setStatus((value) => ({ ...value, session: null })); };
  if (!status) return <div className="jarvis-auth-screen"><div className="auth-scanner" /><p>INITIALIZING SECURE SESSION...</p></div>;
  if (status.security.recoveryRequired) return <div className="jarvis-auth-screen"><section className="jarvis-login-card"><span>SECURITY RECOVERY REQUIRED</span><h1>JARVIS IS LOCKED</h1><p>Use the protected server recovery procedure. No application data is available until recovery is complete.</p></section></div>;
  if (!status.session) return <div className="jarvis-auth-screen"><div className="auth-grid" /><section className="jarvis-login-card"><div className="jarvis-login-mark">J</div><span>JARVIS SECURE ACCESS</span><h1>{resetToken && !resetComplete ? "RESET ADMIN PASSWORD" : forgot ? "ADMIN RECOVERY" : status.security.enabled ? "SELECT SESSION" : "INITIAL ADMIN SETUP"}</h1>
    {resetToken && !resetComplete ? <form onSubmit={completeReset}><label>NEW PASSWORD<input autoFocus type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><label>CONFIRM NEW PASSWORD<input type="password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required /></label>{error && <p className="jarvis-auth-error" role="alert">{error}</p>}<button className="jarvis-login-submit" disabled={busy}>{busy ? "RESETTING..." : "RESET ADMIN PASSWORD"}</button></form>
    : forgot ? <form onSubmit={sendReset}><p>Enter the private Owner email configured by the Admin.</p><label>OWNER EMAIL<input autoFocus type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label>{notice && <p className="security-info" role="status">{notice}</p>}{error && <p className="jarvis-auth-error" role="alert">{error}</p>}<button className="jarvis-login-submit" disabled={busy}>{busy ? "SENDING..." : "SEND RESET CODE"}</button><button type="button" className="auth-link" onClick={() => { setForgot(false); setError(""); setNotice(""); }}>Return to login</button></form>
    : <><p>{status.security.enabled ? "Authenticate to enter the AI Command Center." : "Create the first Admin password and private recovery email. No default credentials are installed."}</p>{status.security.enabled && <div className="session-choices"><button type="button" className={role === "admin" ? "active" : ""} onClick={() => setRole("admin")}><b>ADMIN</b><small>Complete Jarvis access</small></button><button type="button" disabled={!status.childAvailable} className={role === "child" ? "active" : ""} onClick={() => setRole("child")}><b>CHILD</b><small>{status.childAvailable ? "Restricted safe session" : "Not configured"}</small></button>{status.additionalProfilesAvailable && <button type="button" className={role === "additional" ? "active" : ""} onClick={() => setRole("additional")}><b>ADDITIONAL</b><small>Temporary access profile</small></button>}</div>}<form onSubmit={submit}>{role === "additional" && <label>ACCESS PROFILE<select required value={profileId} onChange={(event) => setProfileId(event.target.value)}><option value="">Select profile</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.displayName}</option>)}</select></label>}{!status.security.enabled && <label>OWNER / ADMIN EMAIL<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label>}<label>{status.security.enabled ? `${role.toUpperCase()} PASSWORD` : "NEW ADMIN PASSWORD"}<input autoFocus type="password" autoComplete={status.security.enabled ? "current-password" : "new-password"} value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{!status.security.enabled && <label>CONFIRM ADMIN PASSWORD<input type="password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required /></label>}{notice && <p className="security-info" role="status">{notice}</p>}{error && <p className="jarvis-auth-error" role="alert">{error}</p>}<button className="jarvis-login-submit" disabled={busy}>{busy ? "AUTHENTICATING..." : status.security.enabled ? "ENTER JARVIS" : "CREATE ADMIN SESSION"}</button>{status.security.enabled && role === "admin" && <button type="button" className="auth-link" onClick={() => { setForgot(true); setError(""); setNotice(""); }}>Forgot password?</button>}</form></>}
  </section></div>;
  const session = status.session; const value = { session, can: (permission) => session.role === "admin" || Boolean(session.permissions?.[permission]), refresh, endSession };
  return <AuthContext.Provider value={value}><div className={`jarvis-session-shell role-${session.role}`}>{session.role === "child" && <div className="child-session-indicator">CHILD SESSION</div>}<div className="session-actions"><button type="button" onClick={() => endSession("lock")}>LOCK JARVIS</button><button type="button" onClick={() => endSession("logout")}>LOG OUT</button></div>{children}</div></AuthContext.Provider>;
}
