import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { buildLocalPublishPayload, publishLocalWorkflow, runSingleFlightPublish } from "./localWorkflowPublish.js";

const rules = [4, 6, 9, 11, 15, 19].map((hour, id) => ({ id: `rule-${id}`, interval: "Days", hour: hour < 12 ? `${hour}am` : `${hour - 12}pm`, minute: 0 }));
const nodes = [{ id: "trigger", name: "Schedule Trigger", config: { rules } }, { id: "search", name: "Search Files and Folders", config: { credentialId: "gcred_owner_only" } }, { id: "facebook", name: "Facebook Graph API", config: { credentialId: "fcred_owner_only" } }];
const connections = [{ source: "trigger", target: "search" }, { source: "search", target: "facebook" }];
const source = fs.readFileSync(new URL("./App.jsx", import.meta.url), "utf8");

test("Publish button has a guarded real handler with pending and success state", () => { assert.match(source, /className="publish-button" onClick=\{publishWorkflow\}/); assert.match(source, /runSingleFlightPublish\(publishInFlightRef/); assert.match(source, /setIsPublishing\(true\)/); assert.match(source, /Publishing\.\.\./); assert.match(source, /setWorkflowManagerRefreshKey/); assert.match(source, /Published My Workflow as a server DRAFT/); });

test("double-click publish creates only one request", async () => { const lock = { current: false }; let releases, calls = 0; const pending = new Promise((resolve) => { releases = resolve; }); const first = runSingleFlightPublish(lock, async () => { calls++; await pending; return "created"; }); const second = runSingleFlightPublish(lock, async () => { calls++; return "duplicate"; }); assert.equal(await second, null); assert.equal(calls, 1); releases(); assert.equal(await first, "created"); assert.equal(lock.current, false); });

test("LOCAL publish preserves nodes, connections, rules, timezone, and credential references in a new DRAFT", async () => { const calls = []; const created = { id: "wf_published01", name: "My Workflow", status: "DRAFT", version: 1, nodes, connections, updatedAt: "2026-08-27T00:00:00.000Z" }; const result = await publishLocalWorkflow(async (...args) => { calls.push(args); return { ok: true, status: 201, json: async () => created }; }, "https://jarvis.test", { name: "My Workflow", nodes, connections, timezone: "Asia/Riyadh" }); const payload = JSON.parse(calls[0][1].body); assert.equal(calls.length, 1); assert.equal(calls[0][0], "https://jarvis.test/api/workflows"); assert.equal(calls[0][1].method, "POST"); assert.equal(calls[0][1].credentials, "include"); assert.equal(payload.status, "DRAFT"); assert.deepEqual(payload.nodes, nodes); assert.deepEqual(payload.connections, connections); assert.deepEqual(payload.schedule.rules, rules); assert.equal(payload.timezone, "Asia/Riyadh"); assert.equal(payload.nodes[1].config.credentialId, "gcred_owner_only"); assert.equal(payload.nodes[2].config.credentialId, "fcred_owner_only"); assert.equal(Object.keys(payload).some((key) => /owner|profile/i.test(key)), false); assert.equal(result.id, "wf_published01"); });

test("publishing creates a separate workflow and does not target existing Workflow 2", async () => { const calls = []; await publishLocalWorkflow(async (...args) => { calls.push(args); return { ok: true, status: 201, json: async () => ({ id: "wf_newlocal01" }) }; }, "", { name: "My Workflow", nodes, connections }); assert.equal(calls[0][0], "/api/workflows"); assert.equal(calls[0][1].method, "POST"); assert.doesNotMatch(calls[0][0], /Workflow%202|wf_existing/); assert.equal(JSON.parse(calls[0][1].body).name, "My Workflow"); });

test("repeated publish updates the linked workflow without creating or deactivating it", async () => { const calls = []; const linked = { id: "wf_linked123", name: "Production", status: "ACTIVE", version: 4, nodes, connections }; const result = await publishLocalWorkflow(async (...args) => { calls.push(args); return { ok: true, status: 200, json: async () => linked }; }, "https://corex.test", { name: "Production", nodes, connections, serverWorkflowId: linked.id }); const body = JSON.parse(calls[0][1].body); assert.equal(calls.length, 1); assert.equal(calls[0][0], `https://corex.test/api/workflows/${linked.id}`); assert.equal(calls[0][1].method, "PATCH"); assert.equal(Object.hasOwn(body, "status"), false); assert.equal(result.id, linked.id); });

test("publish validation and API failures are visible and secret-safe", async () => { assert.throws(() => buildLocalPublishPayload({ nodes: [], connections: [] }), /Add workflow nodes/); await assert.rejects(() => publishLocalWorkflow(async () => ({ ok: false, status: 500, json: async () => ({ error: "access_token=secret" }) }), "", { nodes, connections }), (error) => error.message === "Could not publish the workflow. Try again."); });
