import { useEffect, useState } from "react";
import { durationRequest, formatDuration, previewExpiration, profileStatus, validateCustomDuration } from "./securityDuration.js";

const API = import.meta.env.VITE_API_BASE_URL || (import.meta.env.DEV ? "http://localhost:3001" : "");
const PERMISSIONS = [
  ["view_workflow", "Workflow Only"], ["edit_workflow", "Edit workflows"], ["run_workflow", "Run workflows"],
  ["dashboard", "Dashboard"], ["tools", "Tools"], ["storage", "View storage"], ["storage_modify", "Modify storage"],
  ["view_facebook", "View Facebook"], ["publish_facebook", "Publish Facebook"],
];
const emptyPermissions = () => Object.fromEntries(PERMISSIONS.map(([key]) => [key, false]));
async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, { credentials: "include", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || "Security request could not be completed.");
  return data;
}

export default function SecurityAccess() {
  const [status, setStatus] = useState(null); const [profiles, setProfiles] = useState([]); const [notice, setNotice] = useState("");
  const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [profileId, setProfileId] = useState("");
  const [child, setChild] = useState({ displayName: "", password: "", permissions: emptyPermissions() });
  const [durationChoice, setDurationChoice] = useState("none"); const [customDuration, setCustomDuration] = useState("30"); const [customUnit, setCustomUnit] = useState("days");
  const load = async () => { try { const data = await request("/api/security/status"); setStatus(data); if (!data.security?.enabled) { setProfiles([]); return; } const route = data.session?.role === "owner" ? "/api/security/children" : "/api/security/public-profiles"; setProfiles((await request(route)).profiles || []); } catch (error) { setNotice(error.message); } };
  useEffect(() => { void Promise.resolve().then(load); }, []);
  const security = status?.security; const session = status?.session; const owner = session?.role === "owner";
  const customError = durationChoice === "custom" ? validateCustomDuration(customDuration, customUnit) : "";
  const expiresAt = durationChoice !== "none" && !customError ? previewExpiration(durationChoice, customDuration, customUnit) : null;
  const authenticate = async (event) => { event.preventDefault(); setNotice(""); try { if (!security?.enabled) await request("/api/security/setup", { method: "POST", body: JSON.stringify({ password, confirmPassword }) }); else await request("/api/security/login", { method: "POST", body: JSON.stringify({ profileId: profileId || undefined, password }) }); setPassword(""); setConfirmPassword(""); await load(); } catch (error) { setNotice(error.message); } };
  const addChild = async (event) => { event.preventDefault(); setNotice(""); try { await request("/api/security/children", { method: "POST", body: JSON.stringify({ ...child, ...durationRequest(durationChoice, customDuration, customUnit) }) }); setChild({ displayName: "", password: "", permissions: emptyPermissions() }); setDurationChoice("none"); setCustomDuration("30"); setCustomUnit("days"); await load(); } catch (error) { setNotice(error.message); } };
  if (!status) return <section className="security-page"><p role="status">Loading Security &amp; Access…</p></section>;
  return <section className="security-page" aria-labelledby="security-heading">
    <header className="security-heading"><div><span>SECURE LOCAL SESSION</span><h1 id="security-heading">Security &amp; Access</h1><p>Access decisions are enforced by the Jarvis server. Passwords are never displayed or stored in the browser.</p></div>{security.enabled && session && <button className="security-lock" type="button" onClick={async () => { await request("/api/security/lock", { method: "POST" }); await load(); }}>Lock</button>}</header>
    {notice && <p className="security-notice" role="alert">{notice}</p>}
    {security.recoveryRequired ? <article className="security-card setup-security"><h2>Owner Recovery Required</h2><p>Security data needs local owner recovery. Use the server-side recovery procedure; no browser session is granted while recovery is pending.</p></article> : !security.enabled || !session ? <article className="security-card setup-security"><h2>{security.enabled ? "Unlock Jarvis" : "Set up Main Access"}</h2><p className={security.enabled ? "" : "security-info"}>{security.enabled ? "Authenticate with an existing owner or enabled child profile." : "Security is not configured yet."}</p>{!security.enabled && <p>Until an owner completes setup, Jarvis retains its existing local behavior.</p>}<form onSubmit={authenticate}>{security.enabled && <label>Profile<select value={profileId} onChange={(event) => setProfileId(event.target.value)}><option value="">Owner / Admin</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.displayName}</option>)}</select></label>}<label>{security.enabled ? "Password" : "New owner password"}<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{!security.enabled && <label>Confirm password<input type="password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required /></label>}<button className="security-primary">{security.enabled ? "Unlock" : "Enable Security"}</button></form></article> : <>
      <div className="security-grid"><article className="security-card"><h2>Main Access</h2><p><b>{session.displayName}</b> · {session.role === "owner" ? "Full Access" : "Additional Access"}</p><p>{session.expiresAt ? `Session expires ${new Date(session.expiresAt).toLocaleString()}.` : "Session remains active until locked or the browser session ends."}</p><p>Security is enabled with a server-side salted password hash.</p></article><article className="security-card"><h2>Permission Status</h2><div className="security-permission-list">{PERMISSIONS.filter(([key]) => session.permissions?.[key]).length ? PERMISSIONS.filter(([key]) => session.permissions?.[key]).map(([, label]) => <span key={label}>{label}</span>) : <p>No permissions granted.</p>}</div></article></div>
      {owner && <div className="security-grid"><article className="security-card"><h2>Add Additional Access</h2><form onSubmit={addChild}><label>Name<input value={child.displayName} onChange={(event) => setChild({ ...child, displayName: event.target.value })} required /></label><label>Temporary password<input type="password" autoComplete="new-password" value={child.password} onChange={(event) => setChild({ ...child, password: event.target.value })} required /></label><label>Session duration<select value={durationChoice} onChange={(event) => setDurationChoice(event.target.value)}><option value="none">No session expiration</option><option value="minutes:15">15 minutes</option><option value="minutes:60">1 hour</option><option value="minutes:120">2 hours</option><option value="days:1">1 day</option><option value="days:3">3 days</option><option value="days:7">7 days</option><option value="days:30">30 days</option><option value="months:3">3 months</option><option value="months:6">6 months</option><option value="year:1">1 year</option><option value="custom">Custom duration</option></select></label>{durationChoice === "custom" && <div className="custom-duration"><label>Duration<input type="number" min="1" step="1" value={customDuration} onChange={(event) => setCustomDuration(event.target.value)} required /></label><label>Unit<select value={customUnit} onChange={(event) => setCustomUnit(event.target.value)}><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option><option value="year">Year</option></select></label></div>}{customError && <small className="duration-error" role="alert">{customError}</small>}{expiresAt && <p className="duration-preview">Access expires: {new Date(expiresAt).toLocaleString()}</p>}<h3>Permissions</h3>{PERMISSIONS.map(([key, label]) => <label className="permission" key={key}><input type="checkbox" checked={child.permissions[key]} onChange={() => setChild({ ...child, permissions: { ...child.permissions, [key]: !child.permissions[key] } })} />{label}</label>)}<button className="security-primary">Add Access Profile</button></form></article><article className="security-card"><h2>Additional Access</h2>{profiles.length ? profiles.map((profile) => { const state = profileStatus(profile); return <div className="profile-row" key={profile.id}><div><b>{profile.displayName}</b><small>{state} · {formatDuration(profile)}</small>{profile.accessExpiresAt && <small>Expires {new Date(profile.accessExpiresAt).toLocaleDateString()}</small>}</div><button type="button" onClick={async () => { await request(`/api/security/children/${encodeURIComponent(profile.id)}`, { method: "PATCH", body: JSON.stringify({ enabled: !profile.enabled }) }); await load(); }}>{profile.enabled ? "Disable" : "Enable"}</button></div>; }) : <p>No additional access profiles yet.</p>}</article></div>}</>}
  </section>;
}
